CREATE TABLE [dbo].[t_tbmARC_VIDEO_K] (
    [fnINDEX]        BIGINT         NOT NULL,
    [fsFILE_NO]      VARCHAR (16)   NOT NULL,
    [fsTIME]         VARCHAR (16)   NOT NULL,
    [fsTITLE]        NVARCHAR (100) NOT NULL,
    [fsDESCRIPTION]  NVARCHAR (200) NOT NULL,
    [fsFILE_PATH]    NVARCHAR (100) NOT NULL,
    [fsFILE_SIZE]    VARCHAR (50)   NOT NULL,
    [fsFILE_TYPE]    VARCHAR (10)   NOT NULL,
    [fcHEAD_FRAME]   CHAR (1)       NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)   NOT NULL,
    [fdUPDATED_DATE] DATETIME       NULL,
    [fsUPDATED_BY]   VARCHAR (50)   NULL,
    CONSTRAINT [PKt__tbmARC_VIDEO_K] PRIMARY KEY CLUSTERED ([fnINDEX] ASC, [fsFILE_NO] ASC, [fsTIME] ASC)
);

