CREATE TABLE [dbo].[tbdARC_VIDEO_ATTR] (
    [fsFILE_NO]   VARCHAR (16)   NOT NULL,
    [fsCODE_LIST] NVARCHAR (MAX) CONSTRAINT [DF_tbmARC_VIDEO_ATTR_fsCODE_LIST] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_tbdARC_VIDEO_D_ATTR] PRIMARY KEY CLUSTERED ([fsFILE_NO] ASC)
);

