CREATE TABLE [dbo].[tblSRH] (
    [fnSRH_ID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [fsSTATEMENT]    NVARCHAR (MAX) NOT NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_tblSRH] PRIMARY KEY CLUSTERED ([fnSRH_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_1]
    ON [dbo].[tblSRH]([fdCREATED_DATE] ASC, [fsCREATED_BY] ASC);

