CREATE TABLE [dbo].[tblSRH_KW] (
    [fnSRH_ID]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [fsKEYWORD]      NVARCHAR (100) NOT NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_tblSRH_KW_1] PRIMARY KEY CLUSTERED ([fnSRH_ID] ASC)
);

