CREATE TABLE [dbo].[tbmARC_VIDEO_K] (
    [fsFILE_NO]      VARCHAR (16)   NOT NULL,
    [fsTIME]         VARCHAR (16)   NOT NULL,
    [fsTITLE]        NVARCHAR (100) NOT NULL,
    [fsDESCRIPTION]  NVARCHAR (MAX) NOT NULL,
    [fsFILE_PATH]    NVARCHAR (100) NOT NULL,
    [fsFILE_SIZE]    VARCHAR (50)   NOT NULL,
    [fsFILE_TYPE]    VARCHAR (10)   NOT NULL,
    [fcHEAD_FRAME]   CHAR (1)       NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)   NOT NULL,
    [fdUPDATED_DATE] DATETIME       NULL,
    [fsUPDATED_BY]   VARCHAR (50)   NULL,
    CONSTRAINT [PK_tbmARC_VIDEO_K] PRIMARY KEY CLUSTERED ([fsFILE_NO] ASC, [fsTIME] ASC)
);


GO
-- =============================================
-- Author:		<David.Sin>
-- Create date: <2019/05/10>
-- Description:	<關鍵影格異動紀錄觸發程序>
-- =============================================

CREATE TRIGGER [dbo].[trigARC_VIDEO_K_TRAN]
ON [dbo].[tbmARC_VIDEO_K]
FOR INSERT, UPDATE, DELETE
AS
DECLARE @INSERTCOUNT INT, @DELETECOUNT INT, @T_INSERT_NUM INT, @T_DELETE_NUM INT
DECLARE @YEAR INT
IF @@ROWCOUNT = 0 RETURN
SET @T_DELETE_NUM = (SELECT COUNT(*) FROM DELETED)
SET @T_INSERT_NUM = (SELECT COUNT(*) FROM INSERTED)
BEGIN

	INSERT INTO [log].[tbmARC_VIDEO_K]
	SELECT *,'U',GETDATE() ,(SELECT fsUPDATED_BY FROM INSERTED WHERE fsFILE_NO = DELETED.fsFILE_NO) 
	FROM DELETED WHERE fsUPDATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

END
IF (@T_DELETE_NUM > 0 AND @T_INSERT_NUM = 0)
BEGIN

	INSERT INTO [log].[tbmARC_VIDEO_K]
	SELECT *,'D',GETDATE(),CAST(CONTEXT_INFO() AS VARCHAR(50)) FROM DELETED --WHERE fsCREATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

END
IF (@T_DELETE_NUM = 0 AND @T_INSERT_NUM > 0)
BEGIN

	INSERT INTO [log].[tbmARC_VIDEO_K]
	SELECT *,'I',GETDATE(),fsCREATED_BY FROM INSERTED WHERE fsCREATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

END

GO
-- =============================================
-- Author:		<David.Sin>
-- Create date: <2012/04/30>
-- Description:	<Keyframe漸進式索引觸發程序>
-- =============================================

CREATE TRIGGER [dbo].[trigARC_VIDEO_K_INCREMENTAL]
ON dbo.tbmARC_VIDEO_K
FOR INSERT, UPDATE, DELETE
AS
DECLARE @INSERTCOUNT INT, @DELETECOUNT INT, @T_INSERT_NUM INT, @T_DELETE_NUM INT
DECLARE @YEAR INT
IF @@ROWCOUNT = 0 RETURN
SET @T_DELETE_NUM = (SELECT COUNT(*) FROM DELETED)
SET @T_INSERT_NUM = (SELECT COUNT(*) FROM INSERTED)	

--KeyFrame Update才寫入異動
IF (@T_INSERT_NUM > 0 AND @T_DELETE_NUM > 0)
BEGIN
	
	INSERT INTO [dbo].[tbdARC_VIDEO_DIFFERENT](fsSYS_ID,Mode)
		SELECT 
			[tbmARC_VIDEO_D].[fsFILE_NO] + Convert(varchar(3),[tbmARC_VIDEO_D].[fnSEQ_NO]),3
		FROM
			[dbo].[tbmARC_VIDEO_D]
		WHERE
			[tbmARC_VIDEO_D].[fsFILE_NO] IN (SELECT [fsFILE_NO] FROM DELETED)



	INSERT INTO [dbo].[tbdARC_VIDEO_DIFFERENT](fsSYS_ID,Mode)
		SELECT 
			[tbmARC_VIDEO_D].[fsFILE_NO] + Convert(varchar(3),[tbmARC_VIDEO_D].[fnSEQ_NO]),1
		FROM
			[dbo].[tbmARC_VIDEO_D]
		WHERE
			[tbmARC_VIDEO_D].[fsFILE_NO] IN (SELECT [fsFILE_NO] FROM INSERTED)
END
