CREATE TABLE [dbo].[tbmBOOKING] (
    [fnBOOKING_ID]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [fsREASON]       NVARCHAR (100)  NOT NULL,
    [fsDESCRIPTION]  NVARCHAR (1024) NOT NULL,
    [fsPROFILE_V]    VARCHAR (100)   NOT NULL,
    [fsPROFILE_A]    VARCHAR (100)   NOT NULL,
    [fsWATERMARK]    VARCHAR (2)     NOT NULL,
    [fsPATH]         VARCHAR (2)     NOT NULL,
    [fnORDER]        INT             NOT NULL,
    [fsSTATUS]       VARCHAR (2)     NOT NULL,
    [fdCREATED_DATE] DATETIME        NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)    NOT NULL,
    [fdUPDATED_DATE] DATETIME        NULL,
    [fsUPDATED_BY]   VARCHAR (50)    NULL,
    CONSTRAINT [PK_tbmBOOKING] PRIMARY KEY CLUSTERED ([fnBOOKING_ID] ASC) ON [PRIMARY]
) ON [PRIMARY];


GO
CREATE NONCLUSTERED INDEX [IDX_1]
    ON [dbo].[tbmBOOKING]([fsSTATUS] ASC, [fnORDER] ASC)
    ON [PRIMARY];

