CREATE TABLE [dbo].[tbmGROUPS] (
    [fsGROUP_ID]     NVARCHAR (128) NOT NULL,
    [fsNAME]         NVARCHAR (50)  NOT NULL,
    [fsDESCRIPTION]  NVARCHAR (512) NULL,
    [fsTYPE]         NVARCHAR (1)   NULL,
    [fdCREATED_DATE] DATETIME       NULL,
    [fsCREATED_BY]   NVARCHAR (128) NULL,
    [fdUPDATED_DATE] DATETIME       NULL,
    [fsUPDATED_BY]   NVARCHAR (128) NULL,
    [Discriminator]  NVARCHAR (128) NOT NULL,
    CONSTRAINT [PK_dbo.tbmGROUPS] PRIMARY KEY CLUSTERED ([fsGROUP_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RoleNameIndex]
    ON [dbo].[tbmGROUPS]([fsNAME] ASC);


GO

-- =============================================
-- Author:		<David.Sin>
-- Create date: <2019/05/10>
-- Description:	<群組異動紀錄觸發程序>
-- =============================================

CREATE TRIGGER [dbo].[trigGROUP_TRAN]
ON [dbo].[tbmGROUPS]
FOR INSERT, UPDATE, DELETE
AS
DECLARE @INSERTCOUNT INT, @DELETECOUNT INT, @T_INSERT_NUM INT, @T_DELETE_NUM INT
DECLARE @YEAR INT
IF @@ROWCOUNT = 0 RETURN
SET @T_DELETE_NUM = (SELECT COUNT(*) FROM DELETED)
SET @T_INSERT_NUM = (SELECT COUNT(*) FROM INSERTED)
IF (@T_DELETE_NUM > 0 AND @T_INSERT_NUM > 0)
BEGIN

	INSERT INTO [log].[tbmGROUPS]
	SELECT *,'U',GETDATE(),(SELECT fsUPDATED_BY FROM INSERTED WHERE fsGROUP_ID = DELETED.fsGROUP_ID) 
	FROM DELETED WHERE fsUPDATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

END
IF (@T_DELETE_NUM > 0 AND @T_INSERT_NUM = 0)
BEGIN

	INSERT INTO [log].[tbmGROUPS]
	SELECT *,'D',GETDATE(),CAST(CONTEXT_INFO() AS VARCHAR(50)) FROM DELETED

END
IF (@T_DELETE_NUM = 0 AND @T_INSERT_NUM > 0)
BEGIN

	INSERT INTO [log].[tbmGROUPS]
	SELECT *,'I',GETDATE(),fsCREATED_BY FROM INSERTED WHERE fsCREATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

END
