CREATE TABLE [dbo].[tbmGROUPS_bak] (
    [fsGROUP_ID]     VARCHAR (20)   NOT NULL,
    [fsNAME]         NVARCHAR (50)  NOT NULL,
    [fsDESCRIPTION]  NVARCHAR (MAX) NOT NULL,
    [fsTYPE]         CHAR (1)       NOT NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)   NOT NULL,
    [fdUPDATED_DATE] DATETIME       NULL,
    [fsUPDATED_BY]   VARCHAR (50)   NULL,
    CONSTRAINT [PK_tbmGROUPS] PRIMARY KEY CLUSTERED ([fsGROUP_ID] ASC)
);

