CREATE TABLE [dbo].[tbmNOTIFY] (
    [fnNOTIFY_ID]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [fsTITLE]         VARCHAR (50)  NOT NULL,
    [fsCONTENT]       VARCHAR (MAX) NOT NULL,
    [fnCATEGORY]      INT           CONSTRAINT [DF_tbmNOTIFY_fsCATEGORY] DEFAULT ((0)) NOT NULL,
    [fsNOTICE_TARGET] VARCHAR (128) NULL,
    [fdEXPIRE_DATE]   DATETIME      NULL,
    [fdCREATED_DATE]  DATETIME      CONSTRAINT [DF_tbmNOTIFY_fdCREATED_DATE] DEFAULT (getdate()) NOT NULL,
    [fsCREATED_BY]    VARCHAR (50)  NOT NULL,
    [fdUPDATED_DATE]  DATETIME      NULL,
    [fsUPDATED_BY]    VARCHAR (50)  NULL,
    CONSTRAINT [PK_tbmNOTIFY] PRIMARY KEY CLUSTERED ([fnNOTIFY_ID] ASC)
);

