CREATE TABLE [dbo].[tbmTEMPLATE_FIELDS] (
    [fnTEMP_ID]      INT            NOT NULL,
    [fsFIELD]        VARCHAR (50)   NOT NULL,
    [fsFIELD_NAME]   NVARCHAR (50)  NOT NULL,
    [fsFIELD_TYPE]   VARCHAR (50)   NOT NULL,
    [fnFIELD_LENGTH] INT            NULL,
    [fsDESCRIPTION]  NVARCHAR (MAX) NULL,
    [fnORDER]        INT            NOT NULL,
    [fnCTRL_WIDTH]   INT            NULL,
    [fsMULTILINE]    CHAR (1)       NULL,
    [fsISNULLABLE]   CHAR (1)       NULL,
    [fsDEFAULT]      NVARCHAR (50)  NULL,
    [fsCODE_ID]      VARCHAR (20)   NULL,
    [fnCODE_CNT]     INT            NULL,
    [fsCODE_CTRL]    VARCHAR (20)   NULL,
    [fsIS_SEARCH]    CHAR (1)       NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)   NOT NULL,
    [fdUPDATED_DATE] DATETIME       NULL,
    [fsUPDATED_BY]   VARCHAR (50)   NULL,
    CONSTRAINT [PK_tbmTEMPLATE_FIELDS] PRIMARY KEY CLUSTERED ([fnTEMP_ID] ASC, [fsFIELD] ASC)
);


GO
-- =============================================
-- Author:		<David.Sin>
-- Create date: <2019/05/10>
-- Description:	<樣板欄位異動紀錄觸發程序>
-- =============================================

CREATE TRIGGER [dbo].[trigTEMPLATE_FIELDS_TRAN]
ON [dbo].[tbmTEMPLATE_FIELDS]
FOR INSERT, UPDATE, DELETE
AS
DECLARE @INSERTCOUNT INT, @DELETECOUNT INT, @T_INSERT_NUM INT, @T_DELETE_NUM INT
DECLARE @YEAR INT
IF @@ROWCOUNT = 0 RETURN
SET @T_DELETE_NUM = (SELECT COUNT(*) FROM DELETED)
SET @T_INSERT_NUM = (SELECT COUNT(*) FROM INSERTED)
IF (@T_DELETE_NUM > 0 AND @T_INSERT_NUM > 0)
BEGIN

	INSERT INTO [log].[tbmTEMPLATE_FIELDS]
	SELECT *,'U',GETDATE(),(SELECT fsUPDATED_BY FROM INSERTED WHERE fnTEMP_ID = DELETED.fnTEMP_ID AND fsFIELD = DELETED.fsFIELD) 
	FROM DELETED WHERE fsUPDATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

END
IF (@T_DELETE_NUM > 0 AND @T_INSERT_NUM = 0)
BEGIN

	INSERT INTO [log].[tbmTEMPLATE_FIELDS]
	SELECT *,'D',GETDATE(),CAST(CONTEXT_INFO() AS VARCHAR(50)) FROM DELETED

END
IF (@T_DELETE_NUM = 0 AND @T_INSERT_NUM > 0)
BEGIN

	INSERT INTO [log].[tbmTEMPLATE_FIELDS]
	SELECT *,'I',GETDATE(),fsCREATED_BY FROM INSERTED WHERE fsCREATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

END
