CREATE TABLE [dbo].[tbmUSER_GROUP] (
    [fsUSER_ID]       NVARCHAR (128) NOT NULL,
    [fsGROUP_ID]      NVARCHAR (128) NOT NULL,
    [fdCREATED_DATE]  DATETIME       NULL,
    [fsCREATED_BY]    NVARCHAR (128) NULL,
    [fdUPDATED_DATE]  DATETIME       NULL,
    [fsUPDATED_BY]    NVARCHAR (128) NULL,
    [Discriminator]   NVARCHAR (128) NULL,
    [IdentityUser_Id] NVARCHAR (128) NULL,
    CONSTRAINT [PK_dbo.tbmUSER_GROUP] PRIMARY KEY CLUSTERED ([fsUSER_ID] ASC, [fsGROUP_ID] ASC),
    CONSTRAINT [FK_dbo.tbmUSER_GROUP_dbo.tbmGROUPS_fsGROUP_ID] FOREIGN KEY ([fsGROUP_ID]) REFERENCES [dbo].[tbmGROUPS] ([fsGROUP_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dbo.tbmUSER_GROUP_dbo.tbmUSERS_IdentityUser_Id] FOREIGN KEY ([IdentityUser_Id]) REFERENCES [dbo].[tbmUSERS] ([fsUSER_ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_fsGROUP_ID]
    ON [dbo].[tbmUSER_GROUP]([fsGROUP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IdentityUser_Id]
    ON [dbo].[tbmUSER_GROUP]([IdentityUser_Id] ASC);

