CREATE TABLE [dbo].[tbmUSER_DIR] (
    [fsLOGIN_ID]     VARCHAR (50)  NOT NULL,
    [fsDIR_LIST]     VARCHAR (MAX) NOT NULL,
    [fdCREATED_DATE] DATETIME      NULL,
    CONSTRAINT [PK_tbmUSER_DIR] PRIMARY KEY CLUSTERED ([fsLOGIN_ID] ASC)
);

