CREATE TABLE [dbo].[tbmUSER_EXTEND] (
    [fsUSER_ID]            NVARCHAR (128) NOT NULL,
    [fsSIGNALR_CONNECT_ID] NVARCHAR (128) NOT NULL,
    [fdCREATED_DATE]       DATETIME       CONSTRAINT [DF_tbmUSER_EXTEND_fdCREATED_DATE] DEFAULT (getdate()) NOT NULL,
    [fsCREATED_BY]         NVARCHAR (50)  NOT NULL,
    [fdUPDATED_DATE]       DATETIME       NULL,
    [fsUPDATED_BY]         NVARCHAR (50)  NULL,
    CONSTRAINT [PK_tbmUSER_EXTEND] PRIMARY KEY CLUSTERED ([fsUSER_ID] ASC),
    CONSTRAINT [FK_tbmUSER_EXTEND_tbmUSER_EXTEND_UserID] FOREIGN KEY ([fsUSER_ID]) REFERENCES [dbo].[tbmUSERS] ([fsUSER_ID])
);

