CREATE TABLE [dbo].[tbmUSER_FAVORITE] (
    [fsLOGIN_ID] VARCHAR (50) NOT NULL,
    [fsFAVORITE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_tbmUSER_FAVORITE] PRIMARY KEY CLUSTERED ([fsLOGIN_ID] ASC, [fsFAVORITE] ASC)
);

