CREATE TABLE [dbo].[tbmUSER_GROUP_bak] (
    [fnUSER_ID]      BIGINT       NOT NULL,
    [fsGROUP_ID]     VARCHAR (20) NOT NULL,
    [fdCREATED_DATE] DATETIME     NOT NULL,
    [fsCREATED_BY]   VARCHAR (50) NOT NULL,
    [fdUPDATED_DATE] DATETIME     NULL,
    [fsUPDATED_BY]   VARCHAR (50) NULL,
    CONSTRAINT [PK_tbmUSER_GROUP] PRIMARY KEY CLUSTERED ([fnUSER_ID] ASC, [fsGROUP_ID] ASC)
);

