CREATE TABLE [dbo].[tbzCODE] (
    [fsCODE_ID]      VARCHAR (20)   NOT NULL,
    [fsCODE]         VARCHAR (50)   NOT NULL,
    [fsNAME]         NVARCHAR (200) NOT NULL,
    [fsENAME]        VARCHAR (200)  NULL,
    [fnORDER]        INT            NOT NULL,
    [fsSET]          VARCHAR (50)   NULL,
    [fsNOTE]         NVARCHAR (200) NULL,
    [fsIS_ENABLED]   CHAR (1)       NOT NULL,
    [fsTYPE]         CHAR (1)       NOT NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)   NOT NULL,
    [fdUPDATED_DATE] DATETIME       NULL,
    [fsUPDATED_BY]   VARCHAR (50)   NULL,
    CONSTRAINT [PK_tbzCODE] PRIMARY KEY CLUSTERED ([fsCODE_ID] ASC, [fsCODE] ASC)
);


GO
-- =============================================
-- Author:		<David.Sin>
-- Create date: <2019/05/10>
-- Description:	<代碼明細紀錄觸發程序>
-- =============================================

CREATE TRIGGER [dbo].[trigCODE_TRAN]
ON [dbo].[tbzCODE]
FOR INSERT, UPDATE, DELETE
AS
DECLARE @INSERTCOUNT INT, @DELETECOUNT INT, @T_INSERT_NUM INT, @T_DELETE_NUM INT
DECLARE @YEAR INT
IF @@ROWCOUNT = 0 RETURN
SET @T_DELETE_NUM = (SELECT COUNT(*) FROM DELETED)
SET @T_INSERT_NUM = (SELECT COUNT(*) FROM INSERTED)
IF (@T_DELETE_NUM > 0 AND @T_INSERT_NUM > 0)
BEGIN

	INSERT INTO [log].[tbzCODE]
	SELECT *,'U',GETDATE(),(SELECT fsUPDATED_BY FROM INSERTED WHERE fsCODE_ID = DELETED.fsCODE_ID AND fsCODE = DELETED.fsCODE) 
	FROM DELETED WHERE fsUPDATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

	--有用到的影音圖文代碼都要一起更新才能建立異動索引
	DECLARE @t TABLE(fsTYPE CHAR(1),fsSYS_ID VARCHAR(20))

	INSERT INTO @t
	SELECT 'V',fsFILE_NO FROM [dbo].[tbmARC_VIDEO] VDO JOIN
	(
		SELECT [fsSUBJ_ID] FROM [dbo].[tbmSUBJECT] SUBJ JOIN
		(
			SELECT fnDIR_ID FROM [dbo].[tbmDIRECTORIES] A JOIN
			(
				SELECT 
					T.fnTEMP_ID ,T.fsTABLE
				FROM 
					[dbo].[tbmTEMPLATE_FIELDS] TF 
						JOIN [dbo].[tbmTEMPLATE] T ON TF.fnTEMP_ID = T.fnTEMP_ID 
				WHERE 
					[fsFIELD_TYPE] = 'CODE' AND 
					[fsCODE_ID] IN
						(SELECT [fsCODE_ID] FROM INSERTED WHERE fsTYPE = 'C')
			) B ON B.fsTABLE = 'V' AND B.fnTEMP_ID = A.fnTEMP_ID_VIDEO AND A.[fsDIRTYPE] = 'Q'
		) DIR ON SUBJ.fnDIR_ID = DIR.fnDIR_ID
	) TSUBJ ON VDO.fsSUBJECT_ID = TSUBJ.fsSUBJ_ID
	
	--AUDIO
	INSERT INTO @t
	SELECT 'A',fsFILE_NO FROM [dbo].[tbmARC_AUDIO] AUD JOIN
	(
		SELECT [fsSUBJ_ID] FROM [dbo].[tbmSUBJECT] SUBJ JOIN
		(
			SELECT fnDIR_ID FROM [dbo].[tbmDIRECTORIES] A JOIN
			(
				SELECT 
					T.fnTEMP_ID ,T.fsTABLE
				FROM 
					[dbo].[tbmTEMPLATE_FIELDS] TF 
						JOIN [dbo].[tbmTEMPLATE] T ON TF.fnTEMP_ID = T.fnTEMP_ID 
				WHERE 
					[fsFIELD_TYPE] = 'CODE' AND 
					[fsCODE_ID] IN
						(SELECT [fsCODE_ID] FROM INSERTED WHERE fsTYPE = 'C')
			) B ON B.fsTABLE = 'A' AND B.fnTEMP_ID = A.fnTEMP_ID_AUDIO AND A.[fsDIRTYPE] = 'Q'
		) DIR ON SUBJ.fnDIR_ID = DIR.fnDIR_ID
	) TSUBJ ON AUD.fsSUBJECT_ID = TSUBJ.fsSUBJ_ID
	
	
	--PHOTO
	INSERT INTO @t
	SELECT 'P',fsFILE_NO FROM [dbo].[tbmARC_PHOTO] PHO JOIN
	(
		SELECT [fsSUBJ_ID] FROM [dbo].[tbmSUBJECT] SUBJ JOIN
		(
			SELECT fnDIR_ID FROM [dbo].[tbmDIRECTORIES] A JOIN
			(
				SELECT 
					T.fnTEMP_ID ,T.fsTABLE
				FROM 
					[dbo].[tbmTEMPLATE_FIELDS] TF 
						JOIN [dbo].[tbmTEMPLATE] T ON TF.fnTEMP_ID = T.fnTEMP_ID 
				WHERE 
					[fsFIELD_TYPE] = 'CODE' AND 
					[fsCODE_ID] IN
						(SELECT [fsCODE_ID] FROM INSERTED WHERE fsTYPE = 'C')
			) B ON B.fsTABLE = 'P' AND B.fnTEMP_ID = A.fnTEMP_ID_PHOTO AND A.[fsDIRTYPE] = 'Q'
		) DIR ON SUBJ.fnDIR_ID = DIR.fnDIR_ID
	) TSUBJ ON PHO.fsSUBJECT_ID = TSUBJ.fsSUBJ_ID
	
	
	--DOC
	INSERT INTO @t
	SELECT 'D',fsFILE_NO FROM [dbo].[tbmARC_DOC] DOC JOIN
	(
		SELECT [fsSUBJ_ID] FROM [dbo].[tbmSUBJECT] SUBJ JOIN
		(
			SELECT fnDIR_ID FROM [dbo].[tbmDIRECTORIES] A JOIN
			(
				SELECT 
					T.fnTEMP_ID ,T.fsTABLE
				FROM 
					[dbo].[tbmTEMPLATE_FIELDS] TF 
						JOIN [dbo].[tbmTEMPLATE] T ON TF.fnTEMP_ID = T.fnTEMP_ID 
				WHERE 
					[fsFIELD_TYPE] = 'CODE' AND 
					[fsCODE_ID] IN
						(SELECT [fsCODE_ID] FROM INSERTED WHERE fsTYPE = 'C')
			) B ON B.fsTABLE = 'D' AND B.fnTEMP_ID = A.fnTEMP_ID_DOC AND A.[fsDIRTYPE] = 'Q'
		) DIR ON SUBJ.fnDIR_ID = DIR.fnDIR_ID
	) TSUBJ ON DOC.fsSUBJECT_ID = TSUBJ.fsSUBJ_ID
	
	DELETE FROM [dbo].[tbdARC_VIDEO_ATTR] WHERE fsFILE_NO IN (SELECT fsSYS_ID FROM @t WHERE fsTYPE = 'V')
	DELETE FROM [dbo].[tbdARC_AUDIO_ATTR] WHERE fsFILE_NO IN (SELECT fsSYS_ID FROM @t WHERE fsTYPE = 'V')
	DELETE FROM [dbo].[tbdARC_PHOTO_ATTR] WHERE fsFILE_NO IN (SELECT fsSYS_ID FROM @t WHERE fsTYPE = 'V')
	DELETE FROM [dbo].[tbdARC_DOC_ATTR] WHERE fsFILE_NO IN (SELECT fsSYS_ID FROM @t WHERE fsTYPE = 'V')

	INSERT INTO [dbo].[tbdARC_VIDEO_ATTR]([fsFILE_NO],[fsCODE_LIST])
		SELECT fsSYS_ID,
			dbo.fnGET_ARC_USED_NAME_LIST_BY_CODE_LIST(dbo.fnGET_ARC_USED_CODE_LIST_BY_FILE_NO('V',fsSYS_ID))
		FROM
			@t
		WHERE
			fsTYPE = 'V'

	INSERT INTO [dbo].[tbdARC_AUDIO_ATTR]([fsFILE_NO],[fsCODE_LIST])
		SELECT fsSYS_ID,
			dbo.fnGET_ARC_USED_NAME_LIST_BY_CODE_LIST(dbo.fnGET_ARC_USED_CODE_LIST_BY_FILE_NO('A',fsSYS_ID))
		FROM
			@t
		WHERE
			fsTYPE = 'A'
	
	INSERT INTO [dbo].[tbdARC_PHOTO_ATTR]([fsFILE_NO],[fsCODE_LIST])
		SELECT fsSYS_ID,
			dbo.fnGET_ARC_USED_NAME_LIST_BY_CODE_LIST(dbo.fnGET_ARC_USED_CODE_LIST_BY_FILE_NO('P',fsSYS_ID))
		FROM
			@t
		WHERE
			fsTYPE = 'P'

	INSERT INTO [dbo].[tbdARC_DOC_ATTR]([fsFILE_NO],[fsCODE_LIST])
		SELECT fsSYS_ID,
			dbo.fnGET_ARC_USED_NAME_LIST_BY_CODE_LIST(dbo.fnGET_ARC_USED_CODE_LIST_BY_FILE_NO('D',fsSYS_ID))
		FROM
			@t
		WHERE
			fsTYPE = 'D'

	INSERT INTO [dbo].[tbdARC_VIDEO_DIFFERENT]([MODE],[fsSYS_ID]) SELECT 3,fsSYS_ID FROM @t WHERE fsTYPE = 'V'
	INSERT INTO [dbo].[tbdARC_VIDEO_DIFFERENT]([MODE],[fsSYS_ID]) SELECT 1,fsSYS_ID FROM @t WHERE fsTYPE = 'V'
	INSERT INTO [dbo].[tbdARC_AUDIO_DIFFERENT]([MODE],[fsSYS_ID]) SELECT 3,fsSYS_ID FROM @t WHERE fsTYPE = 'A'
	INSERT INTO [dbo].[tbdARC_AUDIO_DIFFERENT]([MODE],[fsSYS_ID]) SELECT 1,fsSYS_ID FROM @t WHERE fsTYPE = 'A'
	INSERT INTO [dbo].[tbdARC_PHOTO_DIFFERENT]([MODE],[fsSYS_ID]) SELECT 3,fsSYS_ID FROM @t WHERE fsTYPE = 'P'
	INSERT INTO [dbo].[tbdARC_PHOTO_DIFFERENT]([MODE],[fsSYS_ID]) SELECT 1,fsSYS_ID FROM @t WHERE fsTYPE = 'P'
	INSERT INTO [dbo].[tbdARC_DOC_DIFFERENT]([MODE],[fsSYS_ID]) SELECT 3,fsSYS_ID FROM @t WHERE fsTYPE = 'D'
	INSERT INTO [dbo].[tbdARC_DOC_DIFFERENT]([MODE],[fsSYS_ID]) SELECT 1,fsSYS_ID FROM @t WHERE fsTYPE = 'D'

END
IF (@T_DELETE_NUM > 0 AND @T_INSERT_NUM = 0)
BEGIN

	INSERT INTO [log].[tbzCODE]
	SELECT *,'D',GETDATE(),CAST(CONTEXT_INFO() AS VARCHAR(50)) FROM DELETED

END
IF (@T_DELETE_NUM = 0 AND @T_INSERT_NUM > 0)
BEGIN

	INSERT INTO [log].[tbzCODE]
	SELECT *,'I',GETDATE(),fsCREATED_BY FROM INSERTED WHERE fsCREATED_BY IN (SELECT fsLOGIN_ID FROM tbmUSERS)

END


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'代碼分類', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'tbzCODE', @level2type = N'COLUMN', @level2name = N'fsTYPE';

