CREATE TABLE [dbo].[tbzCONFIG] (
    [fsKEY]          VARCHAR (50)   CONSTRAINT [DF_tbzCONFIG_fsKEY] DEFAULT ('不可使用空白鍵') NOT NULL,
    [fsVALUE]        NVARCHAR (500) CONSTRAINT [DF_tbzCONFIG_fsVALUE] DEFAULT (N'盡量不要使用空白值') NOT NULL,
    [fsTYPE]         NVARCHAR (50)  NOT NULL,
    [fsDESCRIPTION]  NVARCHAR (500) NOT NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   VARCHAR (50)   NOT NULL,
    [fdUPDATED_DATE] DATETIME       NULL,
    [fsUPDATED_BY]   VARCHAR (50)   NULL,
    CONSTRAINT [PK_tbzCONFIG] PRIMARY KEY CLUSTERED ([fsKEY] ASC)
);

