CREATE TABLE [dbo].[tbzMACHINE_DETAIL] (
    [FSSERVER_NAME]    VARCHAR (255) NOT NULL,
    [FSCPU]            VARCHAR (50)  NULL,
    [FSMEMORY]         VARCHAR (50)  NULL,
    [FSHD_FREEPERCENT] VARCHAR (100) NULL,
    [FSHD_FREEMB]      VARCHAR (100) NULL,
    [FSSEND_NETWORK]   VARCHAR (50)  NULL,
    [FSREAD_NETWORK]   VARCHAR (50)  NULL,
    [FSWEB_USERS]      VARCHAR (3)   NULL,
    [FDUPDATE_TIME]    VARCHAR (20)  NULL,
    CONSTRAINT [PK_TBMACHINE_DETAIL_1] PRIMARY KEY CLUSTERED ([FSSERVER_NAME] ASC)
);

