CREATE TABLE [dbo].[tbzWORKER] (
    [FSWORK_NAME]     VARCHAR (64)  NOT NULL,
    [FSWORKER]        VARCHAR (128) NOT NULL,
    [FDREGISTER_TIME] DATETIME      NOT NULL,
    [FNMASTER]        SMALLINT      NOT NULL
);

