CREATE TABLE [dbo].[xt_tbmINCREMENTAL] (
    [fnINDEX_ID]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [fsDATA_TYPE]    VARCHAR (10)  NOT NULL,
    [fsCODE_ID]      VARCHAR (10)  NOT NULL,
    [fsCODE]         VARCHAR (20)  NOT NULL,
    [fnDIR_ID]       BIGINT        NOT NULL,
    [fsSTATUS]       VARCHAR (2)   NOT NULL,
    [fdCREATED_DATE] DATETIME      NOT NULL,
    [fsCREATED_BY]   NVARCHAR (50) NOT NULL,
    [fdUPDATED_DATE] DATETIME      NOT NULL,
    [fsUPDATED_BY]   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_t_tbmINCREMENTAL] PRIMARY KEY CLUSTERED ([fnINDEX_ID] ASC)
);

