CREATE TABLE [dbo].[xtblTRANSACTION] (
    [fnTRAN_ID]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [fsFILE_NO]      VARCHAR (16)  NOT NULL,
    [fsTABLE_NAME]   VARCHAR (50)  NOT NULL,
    [fsACTION_TYPE]  VARCHAR (50)  NOT NULL,
    [fdCREATED_DATE] DATETIME      NOT NULL,
    [fsCREATED_BY]   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_tblTRACSACTION] PRIMARY KEY CLUSTERED ([fnTRAN_ID] ASC)
);

