CREATE TABLE [dbo].[xtblMESSAGE] (
    [fsMSG_ID]       VARCHAR (36)   CONSTRAINT [DF_tblMESSAGE_fsMSG_ID] DEFAULT (newid()) NOT NULL,
    [fsFROM_ID]      NVARCHAR (50)  NOT NULL,
    [fsTO_ID]        NVARCHAR (50)  NOT NULL,
    [fsINFO]         NVARCHAR (500) NOT NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [_OK]            VARCHAR (1)    NOT NULL,
    [_fnWAIT_ID]     BIGINT         CONSTRAINT [DF_tblMESSAGE__fnWAIT_ID] DEFAULT ((0)) NULL,
    [_fnWORK_ID]     BIGINT         CONSTRAINT [DF_tblMESSAGE__fnWORK_ID] DEFAULT ((0)) NULL,
    [_fsGROUP_ID]    NVARCHAR (50)  CONSTRAINT [DF_tblMESSAGE__fnGROUP_ID] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_tblMESSAGE] PRIMARY KEY CLUSTERED ([fsMSG_ID] ASC)
);

