CREATE TABLE [dbo].[xtblRESTORE] (
    [fnRESTORE_ID]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [fsFILE_NO]      VARCHAR (16)   NOT NULL,
    [fsTYPE]         VARCHAR (1)    NOT NULL,
    [fsTSM_PATH]     VARCHAR (250)  NOT NULL,
    [fsNOTE]         NVARCHAR (500) NOT NULL,
    [fdCREATED_DATE] DATETIME       NOT NULL,
    [fsCREATED_BY]   NVARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_tblRESTORE] PRIMARY KEY CLUSTERED ([fnRESTORE_ID] ASC)
);

