CREATE TABLE [dbo].[xtbmSUBTITLE_T] (
    [fnSUB_T_ID]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [fsNAME]         NVARCHAR (50)   NOT NULL,
    [fsDESCRIPTION]  NVARCHAR (50)   NULL,
    [fsCONTENT]      NVARCHAR (1000) NOT NULL,
    [fdCREATED_DATE] DATETIME        NOT NULL,
    [fsCREATED_BY]   NVARCHAR (50)   NOT NULL,
    [fdUPDATED_DATE] DATETIME        NOT NULL,
    [fsUPDATED_BY]   NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_tbmSUBTITLE_T] PRIMARY KEY CLUSTERED ([fnSUB_T_ID] ASC)
);

