CREATE TABLE [dbo].[xtbtARC_VIDEO] (
    [fsFILE_NO]     VARCHAR (16)   CONSTRAINT [DF_tbtARC_VIDEO_fsFILE_NO] DEFAULT ('') NOT NULL,
    [fsFILE_TYPE]   VARCHAR (10)   CONSTRAINT [DF_tbtARC_VIDEO_fsFILE_TYPE] DEFAULT ('') NOT NULL,
    [fsFILE_TYPE_H] VARCHAR (10)   CONSTRAINT [DF_tbtARC_VIDEO_fsFILE_TYPE_H] DEFAULT ('') NOT NULL,
    [fsFILE_PATH]   NVARCHAR (100) CONSTRAINT [DF_tbtARC_VIDEO_fsFILE_PATH] DEFAULT ('') NOT NULL,
    [fsFILE_PATH_H] NVARCHAR (100) CONSTRAINT [DF_tbtARC_VIDEO_fsFILE_PATH_H] DEFAULT ('') NOT NULL,
    [fxMEDIA_INFO]  NVARCHAR (MAX) CONSTRAINT [DF_tbtARC_VIDEO_fxMEDIA_INFO] DEFAULT ('') NULL,
    [fsPROG_ID]     VARCHAR (10)   CONSTRAINT [DF_tbtARC_VIDEO_fsPROG_ID] DEFAULT ('') NOT NULL,
    [fnEPISODE]     INT            CONSTRAINT [DF_tbtARC_VIDEO_fnEPISODE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_tbtARC_VIDEO] PRIMARY KEY CLUSTERED ([fsFILE_NO] ASC) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];

