CREATE TABLE [dbo].[xtbzRESOLUTION] (
    [fnRESOL_ID]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [fsRATIO]        VARCHAR (10)  NOT NULL,
    [fsNAME]         VARCHAR (20)  NOT NULL,
    [fsWIDTH]        VARCHAR (10)  NOT NULL,
    [fsHEIGHT]       VARCHAR (10)  NOT NULL,
    [fdCREATED_DATE] DATETIME      NOT NULL,
    [fsCREATED_BY]   NVARCHAR (50) NOT NULL,
    [fdUPDATED_DATE] DATETIME      NOT NULL,
    [fsUPDATED_BY]   NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_tbzRESOLUTION] PRIMARY KEY CLUSTERED ([fnRESOL_ID] ASC)
);

