//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmARC_PRE
    {
        public long fnPRE_ID { get; set; }
        public string fsNAME { get; set; }
        public string fsTYPE { get; set; }
        public int fnTEMP_ID { get; set; }
        public string fsTITLE { get; set; }
        public string fsDESCRIPTION { get; set; }
        public System.DateTime fdCREATED_DATE { get; set; }
        public string fsCREATED_BY { get; set; }
        public Nullable<System.DateTime> fdUPDATED_DATE { get; set; }
        public string fsUPDATED_BY { get; set; }
        public string fsATTRIBUTE1 { get; set; }
        public string fsATTRIBUTE2 { get; set; }
        public string fsATTRIBUTE3 { get; set; }
        public string fsATTRIBUTE4 { get; set; }
        public string fsATTRIBUTE5 { get; set; }
        public string fsATTRIBUTE6 { get; set; }
        public string fsATTRIBUTE7 { get; set; }
        public string fsATTRIBUTE8 { get; set; }
        public string fsATTRIBUTE9 { get; set; }
        public string fsATTRIBUTE10 { get; set; }
        public string fsATTRIBUTE11 { get; set; }
        public string fsATTRIBUTE12 { get; set; }
        public string fsATTRIBUTE13 { get; set; }
        public string fsATTRIBUTE14 { get; set; }
        public string fsATTRIBUTE15 { get; set; }
        public string fsATTRIBUTE16 { get; set; }
        public string fsATTRIBUTE17 { get; set; }
        public string fsATTRIBUTE18 { get; set; }
        public string fsATTRIBUTE19 { get; set; }
        public string fsATTRIBUTE20 { get; set; }
        public string fsATTRIBUTE21 { get; set; }
        public string fsATTRIBUTE22 { get; set; }
        public string fsATTRIBUTE23 { get; set; }
        public string fsATTRIBUTE24 { get; set; }
        public string fsATTRIBUTE25 { get; set; }
        public string fsATTRIBUTE26 { get; set; }
        public string fsATTRIBUTE27 { get; set; }
        public string fsATTRIBUTE28 { get; set; }
        public string fsATTRIBUTE29 { get; set; }
        public string fsATTRIBUTE30 { get; set; }
        public string fsATTRIBUTE31 { get; set; }
        public string fsATTRIBUTE32 { get; set; }
        public string fsATTRIBUTE33 { get; set; }
        public string fsATTRIBUTE34 { get; set; }
        public string fsATTRIBUTE35 { get; set; }
        public string fsATTRIBUTE36 { get; set; }
        public string fsATTRIBUTE37 { get; set; }
        public string fsATTRIBUTE38 { get; set; }
        public string fsATTRIBUTE39 { get; set; }
        public string fsATTRIBUTE40 { get; set; }
        public string fsATTRIBUTE41 { get; set; }
        public string fsATTRIBUTE42 { get; set; }
        public string fsATTRIBUTE43 { get; set; }
        public string fsATTRIBUTE44 { get; set; }
        public string fsATTRIBUTE45 { get; set; }
        public string fsATTRIBUTE46 { get; set; }
        public string fsATTRIBUTE47 { get; set; }
        public string fsATTRIBUTE48 { get; set; }
        public string fsATTRIBUTE49 { get; set; }
        public string fsATTRIBUTE50 { get; set; }
        public string fsATTRIBUTE51 { get; set; }
        public string fsATTRIBUTE52 { get; set; }
        public string fsATTRIBUTE53 { get; set; }
        public string fsATTRIBUTE54 { get; set; }
        public string fsATTRIBUTE55 { get; set; }
        public string fsATTRIBUTE56 { get; set; }
        public string fsATTRIBUTE57 { get; set; }
        public string fsATTRIBUTE58 { get; set; }
        public string fsATTRIBUTE59 { get; set; }
        public string fsATTRIBUTE60 { get; set; }
        public string fsHASH_TAG { get; set; }
    }
}
