//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmARC_VIDEO_K
    {
        public string fsFILE_NO { get; set; }
        public string fsTIME { get; set; }
        public string fsTITLE { get; set; }
        public string fsDESCRIPTION { get; set; }
        public string fsFILE_PATH { get; set; }
        public string fsFILE_SIZE { get; set; }
        public string fsFILE_TYPE { get; set; }
        public string fcHEAD_FRAME { get; set; }
        public System.DateTime fdCREATED_DATE { get; set; }
        public string fsCREATED_BY { get; set; }
        public Nullable<System.DateTime> fdUPDATED_DATE { get; set; }
        public string fsUPDATED_BY { get; set; }
    
        public virtual tbmARC_VIDEO tbmARC_VIDEO { get; set; }
    }
}
