//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmCOLUMN_MAPPING
    {
        public string fsTYPE { get; set; }
        public string fsMAIN_COLUMN { get; set; }
        public string fsMAPPING_COLUMN { get; set; }
        public string fsNAME { get; set; }
        public string fsDATATYPE { get; set; }
        public int fnORDER { get; set; }
        public bool fbIS_SEARCH { get; set; }
        public bool fbIS_KEY { get; set; }
    }
}
