//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmDIRECTORIES
    {
        public long fnDIR_ID { get; set; }
        public string fsNAME { get; set; }
        public long fnPARENT_ID { get; set; }
        public string fsDESCRIPTION { get; set; }
        public string fsDIRTYPE { get; set; }
        public int fnORDER { get; set; }
        public int fnTEMP_ID_SUBJECT { get; set; }
        public int fnTEMP_ID_VIDEO { get; set; }
        public int fnTEMP_ID_AUDIO { get; set; }
        public int fnTEMP_ID_PHOTO { get; set; }
        public int fnTEMP_ID_DOC { get; set; }
        public string fsADMIN_GROUP { get; set; }
        public string fsADMIN_USER { get; set; }
        public string fsSHOWTYPE { get; set; }
        public System.DateTime fdCREATED_DATE { get; set; }
        public string fsCREATED_BY { get; set; }
        public Nullable<System.DateTime> fdUPDATED_DATE { get; set; }
        public string fsUPDATED_BY { get; set; }
    }
}
