//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmFUNCTIONS
    {
        public string fsFUNC_ID { get; set; }
        public string fsNAME { get; set; }
        public string fsDESCRIPTION { get; set; }
        public string fsTYPE { get; set; }
        public int fnORDER { get; set; }
        public string fsICON { get; set; }
        public string fsPARENT_ID { get; set; }
        public string fsHEADER { get; set; }
        public string fsCONTROLLER { get; set; }
        public string fsACTION { get; set; }
        public bool fsIS_MULTI_SHEET { get; set; }
        public bool fbIS_QUICK_MENU { get; set; }
        public System.DateTime fdCREATED_DATE { get; set; }
        public string fsCREATED_BY { get; set; }
        public Nullable<System.DateTime> fdUPDATED_DATE { get; set; }
        public string fsUPDATED_BY { get; set; }
    }
}
