//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmRULE_FILTER
    {
        public string fsRULECATEGORY { get; set; }
        public string fsTABLE { get; set; }
        public string fsCOLUMN { get; set; }
        public string fsOPERATOR { get; set; }
        public string fsFILTERVALUE { get; set; }
        public int fnPRIORITY { get; set; }
        public Nullable<bool> fbISENABLED { get; set; }
        public string fsNOTE { get; set; }
        public string fsWHERE_CLAUSE { get; set; }
        public string fsSCRIPTS { get; set; }
        public System.DateTime fdCREATED_DATE { get; set; }
        public string fsCREATED_BY { get; set; }
        public Nullable<System.DateTime> fdUPDATED_DATE { get; set; }
        public string fsUPDATED_BY { get; set; }
    
        public virtual tbmRULE tbmRULE { get; set; }
    }
}
