//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmSUBJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbmSUBJECT()
        {
            this.tbmARC_AUDIO = new HashSet<tbmARC_AUDIO>();
            this.tbmARC_DOC = new HashSet<tbmARC_DOC>();
            this.tbmARC_PHOTO = new HashSet<tbmARC_PHOTO>();
            this.tbmARC_VIDEO = new HashSet<tbmARC_VIDEO>();
        }
    
        public string fsSUBJ_ID { get; set; }
        public string fsTITLE { get; set; }
        public string fsDESCRIPTION { get; set; }
        public long fnDIR_ID { get; set; }
        public string fsTYPE1 { get; set; }
        public string fsTYPE2 { get; set; }
        public string fsTYPE3 { get; set; }
        public string fsATTRIBUTE1 { get; set; }
        public string fsATTRIBUTE2 { get; set; }
        public string fsATTRIBUTE3 { get; set; }
        public string fsATTRIBUTE4 { get; set; }
        public string fsATTRIBUTE5 { get; set; }
        public string fsATTRIBUTE6 { get; set; }
        public string fsATTRIBUTE7 { get; set; }
        public string fsATTRIBUTE8 { get; set; }
        public string fsATTRIBUTE9 { get; set; }
        public string fsATTRIBUTE10 { get; set; }
        public string fsATTRIBUTE11 { get; set; }
        public string fsATTRIBUTE12 { get; set; }
        public string fsATTRIBUTE13 { get; set; }
        public string fsATTRIBUTE14 { get; set; }
        public string fsATTRIBUTE15 { get; set; }
        public string fsATTRIBUTE16 { get; set; }
        public string fsATTRIBUTE17 { get; set; }
        public string fsATTRIBUTE18 { get; set; }
        public string fsATTRIBUTE19 { get; set; }
        public string fsATTRIBUTE20 { get; set; }
        public string fsATTRIBUTE21 { get; set; }
        public string fsATTRIBUTE22 { get; set; }
        public string fsATTRIBUTE23 { get; set; }
        public string fsATTRIBUTE24 { get; set; }
        public string fsATTRIBUTE25 { get; set; }
        public string fsATTRIBUTE26 { get; set; }
        public string fsATTRIBUTE27 { get; set; }
        public string fsATTRIBUTE28 { get; set; }
        public string fsATTRIBUTE29 { get; set; }
        public string fsATTRIBUTE30 { get; set; }
        public string fsATTRIBUTE31 { get; set; }
        public string fsATTRIBUTE32 { get; set; }
        public string fsATTRIBUTE33 { get; set; }
        public string fsATTRIBUTE34 { get; set; }
        public string fsATTRIBUTE35 { get; set; }
        public string fsATTRIBUTE36 { get; set; }
        public string fsATTRIBUTE37 { get; set; }
        public string fsATTRIBUTE38 { get; set; }
        public string fsATTRIBUTE39 { get; set; }
        public string fsATTRIBUTE40 { get; set; }
        public string fsATTRIBUTE41 { get; set; }
        public string fsATTRIBUTE42 { get; set; }
        public string fsATTRIBUTE43 { get; set; }
        public string fsATTRIBUTE44 { get; set; }
        public string fsATTRIBUTE45 { get; set; }
        public string fsATTRIBUTE46 { get; set; }
        public string fsATTRIBUTE47 { get; set; }
        public string fsATTRIBUTE48 { get; set; }
        public string fsATTRIBUTE49 { get; set; }
        public string fsATTRIBUTE50 { get; set; }
        public System.DateTime fdCREATED_DATE { get; set; }
        public string fsCREATED_BY { get; set; }
        public Nullable<System.DateTime> fdUPDATED_DATE { get; set; }
        public string fsUPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmARC_AUDIO> tbmARC_AUDIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmARC_DOC> tbmARC_DOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmARC_PHOTO> tbmARC_PHOTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmARC_VIDEO> tbmARC_VIDEO { get; set; }
    }
}
