//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmTEMPLATE_FIELDS
    {
        public int fnTEMP_ID { get; set; }
        public string fsFIELD { get; set; }
        public string fsFIELD_NAME { get; set; }
        public string fsFIELD_TYPE { get; set; }
        public Nullable<int> fnFIELD_LENGTH { get; set; }
        public string fsDESCRIPTION { get; set; }
        public int fnORDER { get; set; }
        public Nullable<int> fnCTRL_WIDTH { get; set; }
        public string fsMULTILINE { get; set; }
        public string fsISNULLABLE { get; set; }
        public string fsDEFAULT { get; set; }
        public string fsCODE_ID { get; set; }
        public Nullable<int> fnCODE_CNT { get; set; }
        public string fsCODE_CTRL { get; set; }
        public string fsIS_SEARCH { get; set; }
        public System.DateTime fdCREATED_DATE { get; set; }
        public string fsCREATED_BY { get; set; }
        public Nullable<System.DateTime> fdUPDATED_DATE { get; set; }
        public string fsUPDATED_BY { get; set; }
    }
}
