//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRMAM5.DBEntity.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmUSERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbmUSERS()
        {
            this.tbmUSER_GROUP = new HashSet<tbmUSER_GROUP>();
        }
    
        public string fsUSER_ID { get; set; }
        public string fsLOGIN_ID { get; set; }
        public string fsNAME { get; set; }
        public string fsENAME { get; set; }
        public string fsTITLE { get; set; }
        public string fsDEPT_ID { get; set; }
        public string fsDESCRIPTION { get; set; }
        public string fsFILE_SECRET { get; set; }
        public string fsBOOKING_TARGET_PATH { get; set; }
        public string fsEMAIL { get; set; }
        public Nullable<bool> fsIS_ACTIVE { get; set; }
        public Nullable<bool> fsEmailConfirmed { get; set; }
        public string fsPASSWORD { get; set; }
        public string fsSecurityStamp { get; set; }
        public string fsPHONE { get; set; }
        public Nullable<bool> fbPhoneConfirmed { get; set; }
        public Nullable<bool> fbTwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> fdLockoutEndDateUtc { get; set; }
        public Nullable<bool> fbLockoutEnabled { get; set; }
        public Nullable<int> fnAccessFailedCount { get; set; }
        public Nullable<System.DateTime> fdCREATED_DATE { get; set; }
        public string fsCREATED_BY { get; set; }
        public Nullable<System.DateTime> fdUPDATED_DATE { get; set; }
        public string fsUPDATED_BY { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmUSER_GROUP> tbmUSER_GROUP { get; set; }
        public virtual tbmUSER_EXTEND tbmUSER_EXTEND { get; set; }
    }
}
