

-- =============================================
-- 描述:	刪除媒體檔案 BY_TYPE_FILE_NO -將資料搬移到暫存TABLE
-- 記錄:	<2012/04/30><Mihsiu.Chiu><新增本預存>
--    	<2012/09/24><Mihsiu.Chiu><修改預存 t_tbmARC_AUDIO_D新增& fnRESP_ID	fnRELA_ID	fnCHRO_ID	_sEXTRACT>
--    	<2014/04/18><Eric.Huang><修改預存 t_tbmARC_VIDEO / t_tbmARC_VIDEO_D 及相關新增& fsSUBTITLE>
--    	<2014/08/21><Eric.Huang><非EP時才新增下列5個欄位 fsKEYWORD/fsOTHINFO/fsOTHTYPE1/fsOTHTYPE2/fsOTHTYPE3>
--    	<2018/03/28><David.Sin><大改>
--    	<2019/09/11><David.Sin><改成可批次刪除>
-- =============================================
CREATE PROCEDURE [dbo].[spDELETE_ARC_BY_TYPE_FILE_NO]
	@fsTYPE				VARCHAR(1),		--VAPD
	@fsFILE_NOs			VARCHAR(MAX),	--檔案編號
	@fsREASON			VARCHAR(50),	--刪除原因
	@fsDELETED_BY		NVARCHAR(50)	--刪除人員
AS
BEGIN
 	SET NOCOUNT ON;

	BEGIN TRY
		DECLARE @INDEX BIGINT

		DECLARE @t TABLE(fnID INT IDENTITY(1,1),fsFILE_NO VARCHAR(16))
		INSERT INTO @t(fsFILE_NO) SELECT COL1 FROM dbo.fn_SLPIT(@fsFILE_NOs,',')

		DECLARE @i INT = 1
		DECLARE @fnID INT = (SELECT MAX(ISNULL(fnID,0)) FROM @t)

		BEGIN TRANSACTION

		WHILE(@i <= @fnID)
		BEGIN
		
			DECLARE @fsFILE_NO VARCHAR(16) = (SELECT fsFILE_NO FROM @t WHERE fnID = @i)
		
			INSERT INTO t_tbmARC_INDEX(fsFILE_NO, fsTYPE, fsREASON, fsCREATED_BY, fdCREATED_DATE)
			SELECT @fsFILE_NO,@fsTYPE, @fsREASON, @fsDELETED_BY, GETDATE() FROM @t WHERE fnID = @i

			SELECT @INDEX = IDENT_CURRENT('t_tbmARC_INDEX')
		
			DECLARE @context_info VARBINARY(128)
			SET @context_info = CAST(@fsDELETED_BY AS VARBINARY(128))
			SET CONTEXT_INFO @context_info

			IF (@fsTYPE = 'V') 
			BEGIN
			
				INSERT INTO t_tbmARC_VIDEO SELECT @INDEX, * FROM tbmARC_VIDEO WHERE fsFILE_NO = @fsFILE_NO
		
				INSERT INTO t_tbmARC_VIDEO_D SELECT @INDEX,* FROM tbmARC_VIDEO_D WHERE fsFILE_NO = @fsFILE_NO
		
				INSERT INTO t_tbmARC_VIDEO_K SELECT @INDEX,* FROM tbmARC_VIDEO_K WHERE fsFILE_NO = @fsFILE_NO

				INSERT INTO [log].[tbmARC_VIDEO] SELECT * ,'D',GETDATE() FROM [dbo].[tbmARC_VIDEO] WHERE fsFILE_NO = @fsFILE_NO

				--INSERT INTO [dbo].[tblTRANSACTION] SELECT fsFILE_NO,'tbmARC_VIDEO','DELETE',GETDATE(),@fsDELETED_BY FROM [dbo].[tbmARC_VIDEO] WHERE fsFILE_NO = @fsFILE_NO

				DELETE FROM tbmARC_VIDEO_K where fsFILE_NO = @fsFILE_NO
				DELETE FROM tbmARC_VIDEO_D where fsFILE_NO = @fsFILE_NO
				DELETE FROM tbmARC_VIDEO where fsFILE_NO = @fsFILE_NO

			END
			ELSE IF (@fsTYPE = 'A') 
			BEGIN
				INSERT INTO t_tbmARC_AUDIO SELECT @INDEX,* FROM tbmARC_AUDIO WHERE fsFILE_NO = @fsFILE_NO

				INSERT INTO t_tbmARC_AUDIO_D SELECT @INDEX,* FROM tbmARC_AUDIO_D WHERE fsFILE_NO = @fsFILE_NO

				INSERT INTO [log].[tbmARC_AUDIO] SELECT * ,'D',GETDATE() FROM [dbo].[tbmARC_AUDIO] WHERE fsFILE_NO = @fsFILE_NO

				--INSERT INTO [dbo].[tblTRANSACTION] SELECT fsFILE_NO,'tbmARC_AUDIO','DELETE',GETDATE(),@fsDELETED_BY FROM [dbo].[tbmARC_AUDIO] WHERE fsFILE_NO = @fsFILE_NO

				DELETE FROM tbmARC_AUDIO where fsFILE_NO = @fsFILE_NO
				DELETE FROM tbmARC_AUDIO_D where fsFILE_NO = @fsFILE_NO
		   	
			END
			ELSE IF (@fsTYPE = 'P')
			BEGIN
				INSERT INTO t_tbmARC_PHOTO SELECT @INDEX, * FROM tbmARC_PHOTO WHERE fsFILE_NO = @fsFILE_NO

				INSERT INTO [log].[tbmARC_PHOTO] SELECT * ,'D',GETDATE() FROM [dbo].[tbmARC_PHOTO] WHERE fsFILE_NO = @fsFILE_NO
		
				--INSERT INTO [dbo].[tblTRANSACTION] SELECT fsFILE_NO,'tbmARC_PHOTO','DELETE',GETDATE(),@fsDELETED_BY FROM [dbo].[tbmARC_PHOTO] WHERE fsFILE_NO = @fsFILE_NO

				DELETE FROM tbmARC_PHOTO WHERE fsFILE_NO = @fsFILE_NO
			END
			ELSE IF (@fsTYPE = 'D') 
			BEGIN
		   			INSERT INTO t_tbmARC_DOC SELECT @INDEX,* FROM tbmARC_DOC WHERE fsFILE_NO = @fsFILE_NO

					INSERT INTO [log].[tbmARC_DOC] SELECT * ,'D',GETDATE() FROM [dbo].[tbmARC_DOC] WHERE fsFILE_NO = @fsFILE_NO

					--INSERT INTO [dbo].[tblTRANSACTION] SELECT fsFILE_NO,'tbmARC_DOC','DELETE',GETDATE(),@fsDELETED_BY FROM [dbo].[tbmARC_DOC] WHERE fsFILE_NO = @fsFILE_NO

		   			DELETE FROM tbmARC_DOC where fsFILE_NO = @fsFILE_NO
			END

			SET @i += 1

			
		END

		COMMIT
		
		SELECT RESULT = ''
		
	END TRY
	BEGIN CATCH
		
		ROLLBACK

		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH
END

