

-- =============================================
-- 描述:	依照 TEMP_ID 取出TEMPLATE_FIELDS 主檔 資料
-- 記錄:	<2011/10/13><Mihsiu.Chiu><新增本預存>
--      	<2012/09/06><Mihsiu.Chiu><修改fsFIELD_TYPE & Left JOIN>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_TEMPLATE_FIELDS_BY_TEMP_ID]
	@fnTEMP_ID      INT 
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT 
		TEMP_F.fnTEMP_ID, 
		TEMP_F.fsFIELD, 
		TEMP_F.fsFIELD_NAME, 
		TEMP_F.fnFIELD_LENGTH, 
		TEMP_F.fsDESCRIPTION,
		TEMP_F.fnORDER, 
		TEMP_F.fnCTRL_WIDTH, 
		TEMP_F.fsMULTILINE, 
		TEMP_F.fsISNULLABLE, 
		TEMP_F.fsCODE_ID, 
		TEMP_F.fnCODE_CNT, 
		TEMP_F.fsCODE_CTRL,
		TEMP_F.fsIS_SEARCH, 
		TEMP_F.fsDEFAULT,
		TEMP_F.fsFIELD_TYPE,
		--fsFIELD_TYPE = (CASE WHEN (substring(fsFIELD_TYPE,1,4) = 'CUST') then REPLACE(REPLACE(fsFIELD_TYPE, ':ctrl','_'),'_BTN','') --CUST:ctrlNTU_TEAM_BTN
		--				else fsFIELD_TYPE end), 
		_sDEFAULT = (CASE WHEN (fsFIELD_TYPE = 'DATE' OR fsFIELD_TYPE = 'DATETIME') and (fsDEFAULT='S') THEN '系統預設' ELSE fsDEFAULT END), 
		_sLIMIT = (CASE WHEN fsFIELD_TYPE = 'CODE' THEN fnCODE_CNT 
						WHEN fsFIELD_TYPE = 'DATE' OR fsFIELD_TYPE = 'DATETIME' THEN ''
						ELSE fnFIELD_LENGTH END),
		_sFIELD_TYPE_NAME = (CASE WHEN (TEMP_F.fsFIELD_TYPE = '') THEN '(未選擇)' ELSE ISNULL(T.fsNAME, '錯誤代碼: '+TEMP_F.fsFIELD_TYPE) END), 
		_sCODE_SET_NAME = (CASE WHEN (TEMP_F.fsCODE_ID = '') THEN '(未選擇)' ELSE ISNULL(C.fsTITLE, '錯誤代碼: '+TEMP_F.fsCODE_ID) END), 
		TEMP_F.fdCREATED_DATE, 
		TEMP_F.fsCREATED_BY, 
		TEMP_F.fdUPDATED_DATE, 
		TEMP_F.fsUPDATED_BY, 
		_VALUE = '',
		ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
		ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME
	FROM
		tbmTEMPLATE_FIELDS AS TEMP_F
			LEFT JOIN tbzCODE  AS T ON 
				((CASE WHEN (substring(TEMP_F.fsFIELD_TYPE,1,4) = 'CUST') then REPLACE(REPLACE(TEMP_F.fsFIELD_TYPE, ':ctrl','_'),'_BTN','') --CUST:ctrlNTU_TEAM_BTN
					else TEMP_F.fsFIELD_TYPE end) = T.fsCODE) AND T.fsCODE_ID = 'TEMP002'		
			LEFT JOIN tbzCODE_SET AS C ON (TEMP_F.fsCODE_ID = C.fsCODE_ID)					
			LEFT JOIN tbmUSERS USERS_CRT ON TEMP_F.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
			LEFT JOIN tbmUSERS USERS_UPD ON TEMP_F.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID
	WHERE
		(fnTEMP_ID   = @fnTEMP_ID) 
	ORDER BY fnORDER 
END


