

-- =============================================
-- 描述:	取出SYNO主檔資料
-- 記錄:	<2012/05/28><Dennis.Wen><新增預存>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_SYNONYMS]
	@fnINDEX_ID	BIGINT,
	@fsTYPE NVARCHAR(20),
	@fsTEXT NVARCHAR(20)
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT 
		tbmSYNONYMS.fnINDEX_ID, 
		tbmSYNONYMS.fsTEXT_LIST, 
		ISNULL(tbmSYNONYMS.fsTYPE,'') AS fsTYPE,
		tbzCODE.fsNAME AS fsTYPE_NAME, 
		tbmSYNONYMS.fsNOTE,
		tbmSYNONYMS.fdCREATED_DATE, 
		tbmSYNONYMS.fsCREATED_BY, 
		tbmSYNONYMS.fdUPDATED_DATE, 
		tbmSYNONYMS.fsUPDATED_BY,
		ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
		ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME
	FROM
		tbmSYNONYMS 
			LEFT JOIN tbzCODE ON tbmSYNONYMS.fsTYPE = tbzCODE.fsCODE AND tbzCODE.fsCODE_ID = 'SYNO_TYPE'
			LEFT JOIN tbmUSERS USERS_CRT ON tbmSYNONYMS.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
			LEFT JOIN tbmUSERS USERS_UPD ON tbmSYNONYMS.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID
	WHERE
		(@fnINDEX_ID = 0 OR tbmSYNONYMS.fnINDEX_ID = @fnINDEX_ID) AND
		(@fsTYPE = '' OR tbmSYNONYMS.fsTYPE = @fsTYPE) AND
		(@fsTEXT = '' OR tbmSYNONYMS.fsTEXT_LIST LIKE '%'+ @fsTEXT +'%')
	ORDER BY
		fnINDEX_ID
END


