

-- =============================================
-- 描述:	取出TEMPLATE_FIELDS 主檔 資料
-- 記錄:	<2011/09/16><Eric.Huang><新增本預存>
--      	<2011/10/03><Eric.Huang><修改欄位>
--      	<2011/10/07><Mihsiu.Chiu><修改-新增欄位>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_TEMPLATE_FIELDS]
	@fnTEMP_ID      INT ,
	@fsFIELD        VARCHAR(50)
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT 

		TEMP_F.fnTEMP_ID, 
		TEMP_F.fsFIELD, 
		TEMP_F.fsFIELD_NAME, 
		TEMP_F.fsFIELD_TYPE, 
		TEMP_F.fnFIELD_LENGTH, 
		TEMP_F.fsDESCRIPTION,
		TEMP_F.fnORDER, 
		TEMP_F.fnCTRL_WIDTH, 
		TEMP_F.fsMULTILINE, 
		TEMP_F.fsISNULLABLE, 
		TEMP_F.fsCODE_ID, 
		TEMP_F.fnCODE_CNT, 
		TEMP_F.fsCODE_CTRL, 
		TEMP_F.fsDEFAULT,fsIS_SEARCH,
		_sDEFAULT = (CASE WHEN (fsFIELD_TYPE = 'DATE' OR fsFIELD_TYPE = 'DATETIME') and (fsDEFAULT='S') THEN '系統預設' ELSE fsDEFAULT END), 
		_sLIMIT = (CASE WHEN fsFIELD_TYPE = 'CODE' THEN fnCODE_CNT 
						WHEN fsFIELD_TYPE = 'DATE' OR fsFIELD_TYPE = 'DATETIME' THEN ''
						ELSE fnFIELD_LENGTH END),
		_sFIELD_TYPE_NAME = (CASE WHEN (TEMP_F.fsFIELD_TYPE = '') THEN '(未選擇)' ELSE ISNULL(T.fsNAME, '錯誤代碼: '+TEMP_F.fsFIELD_TYPE) END),
		TEMP_F.fdCREATED_DATE, 
		TEMP_F.fsCREATED_BY, 
		TEMP_F.fdUPDATED_DATE, 
		TEMP_F.fsUPDATED_BY, 
		_VALUE = '',
		ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
		ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME
	FROM
		tbmTEMPLATE_FIELDS as TEMP_F
			LEFT JOIN tbzCODE AS T ON (TEMP_F.fsFIELD_TYPE = T.fsCODE) AND T.fsCODE_ID = 'TEMP002'
			LEFT JOIN tbmUSERS USERS_CRT ON TEMP_F.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
			LEFT JOIN tbmUSERS USERS_UPD ON TEMP_F.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID
	WHERE
		(@fnTEMP_ID = 0 OR fnTEMP_ID   = @fnTEMP_ID) AND
		(@fsFIELD = '' OR fsFIELD     = @fsFIELD)
END


