



-- =============================================
-- 描述:	取出DIRECTORIES主檔資料
-- 記錄:	<2011/09/14><Eric.Huang><新增本預存>
-- 記錄:	<2012/12/17><Eric.Huang><新增 fsCATEGORY>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_DIRECTORIES]

	@fnDIR_ID	BIGINT
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT 
		tbmDIRECTORIES.fnDIR_ID,
		tbmDIRECTORIES.fsNAME,
		tbmDIRECTORIES.fnPARENT_ID, 
		tbmDIRECTORIES.fsDESCRIPTION,
		tbmDIRECTORIES.fsDIRTYPE,
		tbmDIRECTORIES.fnORDER,
		tbmDIRECTORIES.fnTEMP_ID_SUBJECT,
		tbmDIRECTORIES.fnTEMP_ID_VIDEO,
		tbmDIRECTORIES.fnTEMP_ID_AUDIO,
		tbmDIRECTORIES.fnTEMP_ID_PHOTO,
		tbmDIRECTORIES.fnTEMP_ID_DOC,
		tbmDIRECTORIES.fsADMIN_GROUP,
		tbmDIRECTORIES.fsADMIN_USER,
		tbmDIRECTORIES.fsSHOWTYPE,
		tbmDIRECTORIES.fdCREATED_DATE,
		tbmDIRECTORIES.fsCREATED_BY, 
		tbmDIRECTORIES.fdUPDATED_DATE,
		tbmDIRECTORIES.fsUPDATED_BY,
		ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
		ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME,
		_SUBJECT_NAME = ISNULL(TEMP_S.fsNAME, ''), 
		_VIDEO_NAME   = ISNULL(TEMP_V.fsNAME, ''), 
		_AUDIO_NAME   = ISNULL(TEMP_A.fsNAME, ''), 
		_PHOTO_NAME   = ISNULL(TEMP_P.fsNAME, ''), 
		_DOC_NAME     = ISNULL(TEMP_D.fsNAME, ''),
		_sGROUP_NAME_LIST = dbo.fnGET_GROUPNAME_FROM_LIST(fsADMIN_GROUP),
		_sUSER_NAME_LIST  = dbo.fnGET_USERNAME_FROM_LIST(fsADMIN_USER),
		_sDIR_PATH = dbo.fnGET_DIR_PATH_BY_DIR_ID(fnDIR_ID)

	FROM
		tbmDIRECTORIES 
			LEFT JOIN tbmTEMPLATE AS TEMP_S ON (TEMP_S.fnTEMP_ID = fnTEMP_ID_SUBJECT)		
			LEFT JOIN tbmTEMPLATE AS TEMP_V ON (TEMP_V.fnTEMP_ID = fnTEMP_ID_VIDEO)
			LEFT JOIN tbmTEMPLATE AS TEMP_A ON (TEMP_A.fnTEMP_ID = fnTEMP_ID_AUDIO)
			LEFT JOIN tbmTEMPLATE AS TEMP_P ON (TEMP_P.fnTEMP_ID = fnTEMP_ID_PHOTO)
			LEFT JOIN tbmTEMPLATE AS TEMP_D ON (TEMP_D.fnTEMP_ID = fnTEMP_ID_DOC)
			LEFT JOIN tbmUSERS USERS_CRT ON tbmDIRECTORIES.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
			LEFT JOIN tbmUSERS USERS_UPD ON tbmDIRECTORIES.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID
	WHERE
		fnDIR_ID = @fnDIR_ID
END




