-- =============================================
-- 描述:	取出上傳轉檔主檔資料 
-- 記錄:	<2019/09/06><David.Sin><新增本預存>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_L_WORK_BY_TRANSCODE]
	@fnWORK_ID		BIGINT,
	@fdBEG_DATE		VARCHAR(10),
	@fdEND_DATE		VARCHAR(10),
	@fsSTATUS		VARCHAR(2)
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT 
		--tblWORK.fnWORK_ID, 
		--tblWORK.fsTYPE, 
		--tblWORK.fsSTATUS, 
		--tblWORK.fsPROGRESS, 
		--tblWORK.fsPRIORITY,
		--tblWORK.fdSTIME, 
		--tblWORK.fdETIME, 
		--tblWORK.fsRESULT, 
		--tblWORK.fsNOTE, 
		--tblWORK.fdCREATED_DATE, 
		--tblWORK.fsCREATED_BY, 
		--tblWORK.fdUPDATED_DATE, 
		--tblWORK.fsUPDATED_BY, 
		--ISNULL(CODE_TYPE.fsNAME, '錯誤') AS _sTYPENAME,
		--ISNULL(CODE_STATUS.fsNAME, '錯誤') AS _sSTATUSNAME,
		--tblWORK.fsPARAMETERS AS _sPARAMETERS2,
		--(dbo.fnGET_WORK_PARAMETERS_ANALYZE(tblWORK.fsPARAMETERS)) fsPARAMETERS,
		--(dbo.fnGET_WORK_PARAMETERS_ANALYZE_UPLOADED_FILE_INFO(tblWORK.fsPARAMETERS)) _sFILE_INFO,
		--(Case when CONVERT(VARCHAR(10),fdSTIME,111) = '1900/01/01' then '-' else CONVERT(VARCHAR(10),fdSTIME,111)+' '+CONVERT(VARCHAR,fdSTIME,108) end) _sSTIME, 
		--(Case when CONVERT(VARCHAR(10),fdETIME,111) = '1900/01/01' then '-' else CONVERT(VARCHAR(10),fdETIME,111)+' '+CONVERT(VARCHAR,fdETIME,108) end) _sETIME,
		--tblWORK.fnGROUP_ID,
		--tblWORK._ITEM_TYPE,
		--tblWORK._ITEM_ID,
		--ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
		--ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME
		tblWORK.fnWORK_ID, 
		tblWORK.fsTYPE, 
		tblWORK.fsSTATUS, 
		tblWORK.fsPROGRESS, 
		tblWORK.fsPRIORITY,
		tblWORK.fdSTIME, 
		tblWORK.fdETIME, 
		tblWORK.fsRESULT, 
		tblWORK.fsNOTE, 
		tblWORK.fdCREATED_DATE, 
		tblWORK.fsCREATED_BY, 
		tblWORK.fdUPDATED_DATE, 
		tblWORK.fsUPDATED_BY, 
		ISNULL(CODE_TYPE.fsNAME, '錯誤') AS _sTYPENAME,
		ISNULL(CODE_STATUS.fsNAME, '錯誤') AS _sSTATUSNAME,
		--解析PARAMETERS
		(dbo.fnGET_WORK_PARAMETERS_ANALYZE(tblWORK.fsPARAMETERS)) fsPARAMETERS,
		(dbo.fnGET_WORK_PARAMETERS_ANALYZE_UPLOADED_FILE_INFO(tblWORK.fsPARAMETERS)) _sFILE_INFO,
		tblWORK.fnGROUP_ID,
		tblWORK._ITEM_TYPE,
		tblWORK._ITEM_ID,
		ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
		ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME
	FROM
		tblWORK 			
			LEFT JOIN tbzCODE CODE_STATUS ON tblWORK.fsSTATUS = CODE_STATUS.fsCODE AND CODE_STATUS.fsCODE_ID = 'WORK_TC'
			LEFT JOIN tbzCODE CODE_TYPE ON tblWORK.fsTYPE = CODE_TYPE.fsCODE AND CODE_TYPE.fsCODE_ID = 'WORK001'
			LEFT JOIN tbmUSERS USERS_CRT ON tblWORK.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
			LEFT JOIN tbmUSERS USERS_UPD ON tblWORK.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID
	WHERE
		tblWORK.fsTYPE = 'TRANSCODE' AND
		(@fnWORK_ID = 0 OR tblWORK.fnWORK_ID = @fnWORK_ID) AND
		(@fsSTATUS = '' OR fsSTATUS = @fsSTATUS) AND
		(@fdBEG_DATE = '' OR CONVERT(VARCHAR(10),tblWORK.fdCREATED_DATE,111) >= @fdBEG_DATE) AND
		(@fdEND_DATE = '' OR CONVERT(VARCHAR(10),tblWORK.fdCREATED_DATE,111) <= @fdEND_DATE)
	ORDER BY
		[fnWORK_ID] DESC
END