



-- =============================================
-- 描述:	依照DIR_ID取出DIRECTORIES主檔資料 BY 管理權限/使用權限 (含顯示欄位為繼承時，要往上找到直接的那一層)
-- 記錄:	<2016/09/13><David.Sin><新增本預存>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_DIRECTORIES_BY_DIR_ID_AUTHORITY]

	@fnDIR_ID	BIGINT,
	@fsTYPE		VARCHAR(1)
	
AS
BEGIN
	SET NOCOUNT ON;
	
CREATE	TABLE #tbDIR_GROUP_USER (	[DATATYPE]		VARCHAR(1),
		[GROUP_ID]		NVARCHAR(128),	[GROUP_NAME]	NVARCHAR(50),
		[USER_ID]		NVARCHAR(128),			[LOGIN_ID]		NVARCHAR(50),	[USER_NAME]		NVARCHAR(50),
		[_ADMIN]		VARCHAR(4),		[_USER]			VARCHAR(1),
		[LIMIT_SUBJECT]	VARCHAR(10),	[LIMIT_VIDEO]	VARCHAR(10),	[LIMIT_AUDIO]	VARCHAR(10),
		[LIMIT_PHOTO]	VARCHAR(10),	[LIMIT_DOC]		VARCHAR(10),   [fnPARENT_ID]	bigint)

	;WITH reADMIN(
		fnDIR_ID,fnPARENT_ID,fsNAME,fsDIRTYPE,fnTEMP_ID_SUBJECT,fnTEMP_ID_VIDEO,fnTEMP_ID_AUDIO,fnTEMP_ID_PHOTO,
		fnTEMP_ID_DOC,fsADMIN_GROUP,fsADMIN_USER,fsSHOWTYPE,fnLEVEL,fnORDER,fsPATH) AS
	(
		SELECT fnDIR_ID,fnPARENT_ID,fsNAME,fsDIRTYPE,fnTEMP_ID_SUBJECT,fnTEMP_ID_VIDEO,fnTEMP_ID_AUDIO,fnTEMP_ID_PHOTO,
		fnTEMP_ID_DOC,fsADMIN_GROUP,fsADMIN_USER,fsSHOWTYPE, 1, 
			fnORDER, CAST(CONVERT(VARCHAR(10),fnDIR_ID) AS VARCHAR(MAX)) FROM tbmDIRECTORIES WHERE fnDIR_ID = @fnDIR_ID
		UNION ALL
		SELECT A.fnDIR_ID,A.fnPARENT_ID,A.fsNAME,A.fsDIRTYPE,A.fnTEMP_ID_SUBJECT,A.fnTEMP_ID_VIDEO,A.fnTEMP_ID_AUDIO,A.fnTEMP_ID_PHOTO,
		A.fnTEMP_ID_DOC,A.fsADMIN_GROUP,A.fsADMIN_USER,A.fsSHOWTYPE, (B.fnLEVEL - 1), 
			A.fnORDER, CAST(B.fsPATH + CAST('/' + CONVERT(VARCHAR(10),A.fnDIR_ID) AS VARCHAR(1024)) AS VARCHAR(MAX)) FROM tbmDIRECTORIES A JOIN reADMIN B ON B.fnPARENT_ID = A.fnDIR_ID
	)

	--把樹&_ADMIN& _USER新增至#tbResult
	SELECT *, '' AS _ADMIN, '' AS _USER INTO #tbResult FROM reADMIN ORDER BY fnLEVEL

	INSERT
		#tbDIR_GROUP_USER
	---以下是把有設定在[DIRECTORIES]目錄fsADMIN_GROUP欄的群組加入
	SELECT	'G', fsGROUP_ID, G.fsNAME, '', '', '', '', '',	'', '', '',	'', '', 0
	FROM	tbmGROUPS AS G JOIN #tbResult B ON B.fsADMIN_GROUP LIKE '%'+G.fsGROUP_ID+';%'

	---以下是把有設定在[tbmDIR_GROUP]目錄fsADMIN_GROUP欄的群組加入
		UNION
	SELECT	DISTINCT 'G', G.fsGROUP_ID, G.fsNAME, '', '', '',	'', '',	'', '', '',	'', '', 0
	FROM	tbmGROUPS AS G JOIN tbmDIR_GROUP AS DG ON (DG.fsGROUP_ID = G.fsGROUP_ID)
							JOIN #tbResult B ON DG.fnDIR_ID = B.fnDIR_ID
	
	---以下是把有設定在[DIRECTORIES]目錄fsADMIN_USER欄的群組加入
		UNION		
	SELECT	'U', '', '', fsUSER_ID, fsLOGIN_ID, U.fsNAME, '', '',	'', '', '',	'', '', 0
	FROM	dbo.tbmUSERS AS U JOIN #tbResult A ON A.fsADMIN_USER LIKE '%'+ U.fsLOGIN_ID+';%'

	---以下是把有設定在[tbmDIR_USER]目錄fsADMIN_GROUP欄的群組加入
		UNION
	SELECT	'U', '', '', U.fsUSER_ID, U.fsLOGIN_ID, U.fsNAME, '', '',	'', '', '',	'', '', 0
	FROM	dbo.tbmUSERS AS U JOIN tbmDIR_USER AS DU ON (DU.fsLOGIN_ID = U.fsLOGIN_ID)
							JOIN #tbResult B ON DU.fnDIR_ID = B.fnDIR_ID
	
	

	IF (@fsTYPE = 'G')
	BEGIN
		
		--處理直接的管理，只處理#tbDIR_GROUP_USER中，符合選取節點&是fsADMIN_GROUP的群組
		UPDATE
			#tbDIR_GROUP_USER
		SET
			_ADMIN = 'Y',
			LIMIT_SUBJECT = 'V,I,U,D,B',
			LIMIT_VIDEO = 'V,I,U,D,B',
			LIMIT_AUDIO = 'V,I,U,D,B',
			LIMIT_PHOTO = 'V,I,U,D,B',
			LIMIT_DOC = 'V,I,U,D,B'
		WHERE
			DATATYPE = @fsTYPE AND
			EXISTS(SELECT fnDIR_ID FROM #tbDIR_GROUP_USER AS G JOIN #tbResult B ON B.fsADMIN_GROUP LIKE '%'+ G.GROUP_ID+';%' WHERE B.fnDIR_ID = @fnDIR_ID AND #tbDIR_GROUP_USER.GROUP_ID = G.GROUP_ID)

		--處理繼承的管理，只處理#tbDIR_GROUP_USER中，非直接管理&是fsADMIN_GROUP的群組
		UPDATE
			#tbDIR_GROUP_USER
		SET
			_ADMIN = 'y',
			LIMIT_SUBJECT = 'V,I,U,D,B',
			LIMIT_VIDEO = 'V,I,U,D,B',
			LIMIT_AUDIO = 'V,I,U,D,B',
			LIMIT_PHOTO = 'V,I,U,D,B',
			LIMIT_DOC = 'V,I,U,D,B'
		WHERE
			DATATYPE = @fsTYPE AND
			#tbDIR_GROUP_USER._ADMIN <> 'Y' AND 
			EXISTS(SELECT fnDIR_ID FROM #tbDIR_GROUP_USER AS G JOIN #tbResult B ON B.fsADMIN_GROUP LIKE '%'+ G.GROUP_ID+';%' AND #tbDIR_GROUP_USER.GROUP_ID = G.GROUP_ID WHERE B.fnDIR_ID <> @fnDIR_ID)
			
		--處理直接的顯示，只處理#tbDIR_GROUP_USER中，符合選取節點&是tbmDIR_GROUP的群組
		UPDATE
			#tbDIR_GROUP_USER
		SET
			_USER = 'Y',
			LIMIT_SUBJECT = 
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_SUBJECT
					ELSE LIMIT_SUBJECT
				END,
			LIMIT_VIDEO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_VIDEO
					ELSE LIMIT_VIDEO
				END,
			LIMIT_AUDIO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_AUDIO
					ELSE LIMIT_AUDIO
				END,
			LIMIT_PHOTO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_PHOTO
					ELSE LIMIT_PHOTO
				END,
			LIMIT_DOC =		
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_DOC
					ELSE LIMIT_DOC
				END
		FROM #tbDIR_GROUP_USER AS G JOIN tbmDIR_GROUP B ON G.GROUP_ID = B.fsGROUP_ID AND B.fnDIR_ID = @fnDIR_ID
		WHERE
			DATATYPE = @fsTYPE

		--處理繼承顯示，只處理#tbDIR_GROUP_USER中，非直接顯示&是tbmDIR_GROUP的群組
		UPDATE
			#tbDIR_GROUP_USER
		SET
			_USER = 'y',
			LIMIT_SUBJECT = 
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_SUBJECT
					ELSE LIMIT_SUBJECT
				END,
			LIMIT_VIDEO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_VIDEO
					ELSE LIMIT_VIDEO
				END,
			LIMIT_AUDIO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_AUDIO
					ELSE LIMIT_AUDIO
				END,
			LIMIT_PHOTO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_PHOTO
					ELSE LIMIT_PHOTO
				END,
			LIMIT_DOC =		
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_DOC
					ELSE LIMIT_DOC
				END
		FROM
			#tbDIR_GROUP_USER AS G JOIN tbmDIR_GROUP B ON G.GROUP_ID = B.fsGROUP_ID
									JOIN #tbResult C ON B.fnDIR_ID = C.fnDIR_ID AND C.fnDIR_ID <> @fnDIR_ID
		WHERE
			DATATYPE = @fsTYPE AND G._USER <> 'Y'
			
		SELECT *,
			_sDIR_PATH = dbo.fnGET_DIR_PATH_BY_DIR_ID(@fnDIR_ID),
			@fnDIR_ID AS fnDIR_ID
		FROM #tbDIR_GROUP_USER WHERE DATATYPE = @fsTYPE

	END

	ELSE IF (@fsTYPE = 'U')
	BEGIN
		
		--處理直接的管理
		UPDATE
			#tbDIR_GROUP_USER
		SET
			_ADMIN = 'Y',
			LIMIT_SUBJECT = 'V,I,U,D,B',
			LIMIT_VIDEO = 'V,I,U,D,B',
			LIMIT_AUDIO = 'V,I,U,D,B',
			LIMIT_PHOTO = 'V,I,U,D,B',
			LIMIT_DOC = 'V,I,U,D,B'
		WHERE
			DATATYPE = @fsTYPE AND
			EXISTS(SELECT fnDIR_ID FROM #tbDIR_GROUP_USER AS G JOIN #tbResult B ON B.fsADMIN_USER LIKE '%'+ G.LOGIN_ID+';%' WHERE B.fnDIR_ID = @fnDIR_ID AND #tbDIR_GROUP_USER.USER_ID = G.USER_ID)

		--處理繼承的管理
		UPDATE
			#tbDIR_GROUP_USER
		SET
			_ADMIN = 'y',
			LIMIT_SUBJECT = 'V,I,U,D,B',
			LIMIT_VIDEO = 'V,I,U,D,B',
			LIMIT_AUDIO = 'V,I,U,D,B',
			LIMIT_PHOTO = 'V,I,U,D,B',
			LIMIT_DOC = 'V,I,U,D,B'
		WHERE
			DATATYPE = @fsTYPE AND
			#tbDIR_GROUP_USER._ADMIN <> 'Y' AND 
			EXISTS(SELECT fnDIR_ID FROM #tbDIR_GROUP_USER AS G JOIN #tbResult B ON B.fsADMIN_USER LIKE '%'+ G.LOGIN_ID+';%' AND #tbDIR_GROUP_USER.USER_ID = G.USER_ID)
			
		--處理直接的顯示
		UPDATE
			#tbDIR_GROUP_USER
		SET
			_USER = 'Y',
			LIMIT_SUBJECT = 
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_SUBJECT
					ELSE LIMIT_SUBJECT
				END,
			LIMIT_VIDEO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_VIDEO
					ELSE LIMIT_VIDEO
				END,
			LIMIT_AUDIO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_AUDIO
					ELSE LIMIT_AUDIO
				END,
			LIMIT_PHOTO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_PHOTO
					ELSE LIMIT_PHOTO
				END,
			LIMIT_DOC =		
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_DOC	
					ELSE LIMIT_DOC
				END
		FROM #tbDIR_GROUP_USER AS G JOIN tbmDIR_USER B ON G.[LOGIN_ID] = B.fsLOGIN_ID AND B.fnDIR_ID = @fnDIR_ID
									JOIN #tbResult C ON B.fnDIR_ID = C.fnDIR_ID
		WHERE
			DATATYPE = @fsTYPE

		--處理繼承顯示
		UPDATE
			#tbDIR_GROUP_USER
		SET
			_USER = 'y',
			LIMIT_SUBJECT = 
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_SUBJECT
					ELSE LIMIT_SUBJECT
				END,
			LIMIT_VIDEO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_VIDEO
					ELSE LIMIT_VIDEO
				END,
			LIMIT_AUDIO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_AUDIO
					ELSE LIMIT_AUDIO
				END,
			LIMIT_PHOTO =	
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_PHOTO
					ELSE LIMIT_PHOTO
				END,
			LIMIT_DOC =		
				CASE G._ADMIN
					WHEN '' THEN B.fsLIMIT_DOC	
					ELSE LIMIT_DOC
				END
		FROM
			#tbDIR_GROUP_USER AS G JOIN tbmDIR_USER B ON G.[LOGIN_ID] = B.fsLOGIN_ID
									JOIN #tbResult C ON B.fnDIR_ID = C.fnDIR_ID AND C.fnDIR_ID <> @fnDIR_ID

		WHERE
			DATATYPE = @fsTYPE AND G._USER <> 'Y'
		
		
		SELECT *,
			_sDIR_PATH = dbo.fnGET_DIR_PATH_BY_DIR_ID(@fnDIR_ID),
			@fnDIR_ID AS fnDIR_ID
		FROM #tbDIR_GROUP_USER WHERE DATATYPE = @fsTYPE


	END


	DROP TABLE #tbDIR_GROUP_USER

	DROP TABLE #tbResult
END



