



-- =============================================
-- 描述:	依照TEMPLATE ID 取出DIRECTORIES主檔資料
-- 記錄:	<2011/10/14><Mihsiu.Chiu><新增本預存>
-- 記錄:	<2015/06/03><Eric.Huang><修改本預存-因為只是去取出有沒有DIR使用此樣版,故取前10筆即可,要不然一次取上百筆會取不回fnGET_DIR_PATH_BY_DIR_ID>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_DIRECTORIES_BY_TEMP_ID]
	@fnTEMP_ID_SUBJECT	BIGINT,
	@fnTEMP_ID_VIDEO	BIGINT,
	@fnTEMP_ID_AUDIO	BIGINT,
	@fnTEMP_ID_PHOTO	BIGINT,
	@fnTEMP_ID_DOC		BIGINT
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT TOP 10
			tbmDIRECTORIES.fnDIR_ID, 
			tbmDIRECTORIES.fsNAME, 
			tbmDIRECTORIES.fnPARENT_ID, 
			tbmDIRECTORIES.fsDESCRIPTION, 
			tbmDIRECTORIES.fsDIRTYPE, 
			tbmDIRECTORIES.fnORDER,
			tbmDIRECTORIES.fnTEMP_ID_SUBJECT, 
			tbmDIRECTORIES.fnTEMP_ID_VIDEO, 
			tbmDIRECTORIES.fnTEMP_ID_AUDIO,
			tbmDIRECTORIES.fnTEMP_ID_PHOTO,
			tbmDIRECTORIES.fnTEMP_ID_DOC, 
			tbmDIRECTORIES.fsADMIN_GROUP, 
			tbmDIRECTORIES.fsADMIN_USER, 
			tbmDIRECTORIES.fsSHOWTYPE, 
			tbmDIRECTORIES.fdCREATED_DATE,
			tbmDIRECTORIES.fsCREATED_BY, 
			tbmDIRECTORIES.fdUPDATED_DATE, 
			tbmDIRECTORIES.fsUPDATED_BY,
			ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
			ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME,
			_sDIR_PATH = dbo.fnGET_DIR_PATH_BY_DIR_ID(tbmDIRECTORIES.fnDIR_ID)

	FROM
		tbmDIRECTORIES
			LEFT JOIN tbmUSERS USERS_CRT ON tbmDIRECTORIES.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
			LEFT JOIN tbmUSERS USERS_UPD ON tbmDIRECTORIES.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID
	WHERE
		((@fnTEMP_ID_SUBJECT = 0) OR (fnTEMP_ID_SUBJECT = @fnTEMP_ID_SUBJECT)) AND
		((@fnTEMP_ID_VIDEO = 0) OR (fnTEMP_ID_VIDEO = @fnTEMP_ID_VIDEO)) AND
		((@fnTEMP_ID_AUDIO = 0) OR (fnTEMP_ID_AUDIO = @fnTEMP_ID_AUDIO)) AND
		((@fnTEMP_ID_PHOTO = 0) OR (fnTEMP_ID_PHOTO = @fnTEMP_ID_PHOTO)) AND
		((@fnTEMP_ID_DOC = 0) OR (fnTEMP_ID_DOC = @fnTEMP_ID_DOC))  AND
		(@fnTEMP_ID_SUBJECT > 0 OR @fnTEMP_ID_VIDEO > 0 OR @fnTEMP_ID_AUDIO > 0 OR @fnTEMP_ID_PHOTO > 0 OR @fnTEMP_ID_DOC > 0)
END




