


-- =============================================
-- 描述:	取出L_WORK主檔資料
-- 記錄:	<2011/11/22><Mihsiu.Chiu><新增本預存>
--      	<2011/11/29><Eric.Huang><新增欄位>
--       	<2012/01/13><Eric.Huang><新增:解析PARAMETERS後放回原本的PARAMETERS裡>
--			<2012/04/18><Mihsiu.Chiu><新增欄位-fnGROUP_ID>
--			<2016/11/18><David.Sin><修改SP>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_L_WORK]
	@fnWORK_ID		BIGINT,
	@fnGROUP_ID		BIGINT,
	@fsTYPE			VARCHAR(200),
	@fsSTATUS		VARCHAR(2),
	@fdBEG_DATE		VARCHAR(10),
	@fdEND_DATE		VARCHAR(10)
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT 
			tblWORK.fnWORK_ID, 
			tblWORK.fsTYPE, 
			tblWORK.fsSTATUS, 
			tblWORK.fsPROGRESS, 
			tblWORK.fsPRIORITY,
			tblWORK.fdSTIME, 
			tblWORK.fdETIME, 
			tblWORK.fsRESULT, 
			tblWORK.fsNOTE, 
			tblWORK.fdCREATED_DATE, 
			tblWORK.fsCREATED_BY, 
			tblWORK.fdUPDATED_DATE, 
			tblWORK.fsUPDATED_BY, 
			ISNULL(CODE_TYPE.fsNAME, '錯誤') AS _sTYPENAME,
			CASE tblWORK.fsTYPE
				WHEN 'TRANSCODE' THEN (SELECT fsNAME FROM tbzCODE WHERE fsCODE_ID = 'WORK_TC' AND fsCODE = fsSTATUS)
				WHEN 'DAILY_ITP' THEN (SELECT fsNAME FROM tbzCODE WHERE fsCODE_ID = 'WORK_TC' AND fsCODE = fsSTATUS)
				WHEN 'BOOKING' THEN (SELECT fsNAME FROM tbzCODE WHERE fsCODE_ID = 'WORK_BK' AND fsCODE = fsSTATUS)
				WHEN 'COPYFILE' THEN (SELECT fsNAME FROM tbzCODE WHERE fsCODE_ID = 'WORK_BK' AND fsCODE = fsSTATUS)
				WHEN 'AVID' THEN (SELECT fsNAME FROM tbzCODE WHERE fsCODE_ID = 'WORK_BK' AND fsCODE = fsSTATUS)
				WHEN 'NAS' THEN (SELECT fsNAME FROM tbzCODE WHERE fsCODE_ID = 'WORK_BK' AND fsCODE = fsSTATUS)
			END AS _sSTATUSNAME,
			--解析PARAMETERS
			(dbo.fnGET_WORK_PARAMETERS_ANALYZE(tblWORK.fsPARAMETERS)) fsPARAMETERS,
			(dbo.fnGET_WORK_PARAMETERS_ANALYZE_UPLOADED_FILE_INFO(tblWORK.fsPARAMETERS)) _sFILE_INFO,
			tblWORK.fnGROUP_ID,
			tblWORK._ITEM_TYPE,
			tblWORK._ITEM_ID,
			ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
			ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME
		FROM
			tblWORK			
				LEFT JOIN tbzCODE AS CODE_TYPE ON (tblWORK.fsTYPE = CODE_TYPE.fsCODE) AND fsCODE_ID = 'WORK001'					
				LEFT JOIN tbmUSERS USERS_CRT ON tblWORK.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
				LEFT JOIN tbmUSERS USERS_UPD ON tblWORK.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID
		WHERE
			(@fnWORK_ID = 0 OR fnWORK_ID = @fnWORK_ID) AND
			(@fnGROUP_ID = 0 OR fnGROUP_ID = @fnGROUP_ID) AND
			(@fsTYPE = '' OR tblWORK.fsTYPE IN (SELECT COL1 FROM [dbo].[fn_SLPIT](@fsTYPE,','))) AND
			(@fsSTATUS = '' OR fsSTATUS = @fsSTATUS) AND
			(@fdBEG_DATE = '' OR CONVERT(VARCHAR(10),tblWORK.fdCREATED_DATE,111) >= @fdBEG_DATE) AND
			(@fdEND_DATE = '' OR CONVERT(VARCHAR(10),tblWORK.fdCREATED_DATE,111) <= @fdEND_DATE)
		ORDER BY
			[fnWORK_ID] DESC
END



