

-- =============================================
-- 描述:	取出USERS主檔資料
-- 記錄:	<2011/08/22><Mihsiu.Chiu><新增本預存>
-- 記錄:	<2011/08/24><Eric.Huang><新增 fsPHONE/fdSDATE/fdEDATE/fsTYPE/_fsTYPENAME>
-- 記錄:	<2016/10/21><David.Sin><增加篩選條件>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_USERS]
	@fsUSER_ID	NVARCHAR(128),
	@fsLOGIN_ID	NVARCHAR(50),
	@fsNAME	    NVARCHAR(50) 
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT 
		fsUSER_ID,
		fsLOGIN_ID,
		fsPASSWORD,
		fsNAME,
		fsENAME,
		fsTITLE, 
		fsDEPT_ID,
		fsEMAIL,
		fsPHONE,
		fsDESCRIPTION,
		fsFILE_SECRET,
		fsBOOKING_TARGET_PATH,
		fsIS_ACTIVE,
		fdCREATED_DATE,
		fsCREATED_BY,
		fdUPDATED_DATE,
		fsUPDATED_BY,
		_sDEPTNAME,
		CASE 
			WHEN LEN(fsGROUPs) > 0 THEN SUBSTRING(fsGROUPs,1,LEN(fsGROUPs) - 1) 
			ELSE ''
		END AS fsGROUPs,
		_sIS_ADMINS,
		fsCREATED_BY_NAME,
		fsUPDATED_BY_NAME
	FROM
	(
		SELECT 
			USERS.fsUSER_ID,
			USERS.fsLOGIN_ID,
			USERS.fsPASSWORD,
			USERS.fsNAME,
			USERS.fsENAME,
			USERS.fsTITLE, 
			USERS.fsDEPT_ID,
			USERS.fsEMAIL,
			USERS.fsPHONE,
			USERS.fsDESCRIPTION,
			USERS.fsFILE_SECRET,
			ISNULL(USERS.fsBOOKING_TARGET_PATH,'') AS fsBOOKING_TARGET_PATH,
			USERS.fsIS_ACTIVE,
			USERS.fdCREATED_DATE,
			USERS.fsCREATED_BY,
			ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
			USERS.fdUPDATED_DATE,
			USERS.fsUPDATED_BY,
			ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME,
			ISNULL(D.fsNAME, '') AS _sDEPTNAME,
			CASE 
				WHEN LEN(@fsUSER_ID) > 0 OR LEN(@fsLOGIN_ID) > 0 THEN (SELECT fsGROUP_ID + ';' FROM tbmUSER_GROUP WHERE fsUSER_ID = USERS.fsUSER_ID FOR XML PATH(''))
				ELSE ''
			END AS fsGROUPs,
			(
				SELECT CASE WHEN COUNT(G.fsGROUP_ID) > 0 THEN 'Y' ELSE 'N' END 
				FROM 
				tbmGROUPS G JOIN
				tbmUSER_GROUP U ON G.fsGROUP_ID = U.fsGROUP_ID AND U.fsUSER_ID = USERS.fsUSER_ID JOIN
				(
					SELECT COL1 FROM dbo.fn_SLPIT((SELECT fsVALUE FROM tbzCONFIG WHERE fsKEY = 'ADMIN_GROUPS'),';')
				) T ON G.fsGROUP_ID = T.COL1
			) AS _sIS_ADMINS
		FROM
			tbmUSERS AS USERS
				LEFT JOIN tbmUSERS AS USERS_CRT ON USERS.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
				LEFT JOIN tbmUSERS AS USERS_UPD ON USERS.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID
				LEFT JOIN tbzCODE  AS D ON (USERS.fsDEPT_ID = D.fsCODE)	AND D.fsCODE_ID = 'DEPT001'
				
		WHERE
			(@fsUSER_ID = '' OR USERS.fsUSER_ID = @fsUSER_ID) AND
			(@fsLOGIN_ID = '' OR USERS.fsLOGIN_ID LIKE @fsLOGIN_ID + '%') AND
			(@fsNAME = '' OR USERS.fsNAME LIKE @fsNAME + '%')
	) T
END


