

-- =============================================
-- 描述:	取出SUBJECT 媒資主檔 資料
-- 記錄:	<2011/09/15><Eric.Huang><新增本預存>
--			<2012/04/12><Mihsiu.Chiu><新增欄位_sGROUP_NAME_LIST/_sTYPE1/_sTYPE2/_sTYPE3>
--			<2012/07/24><Eric.Huang><新增欄位 fnRESP_ID/fnRELA_ID/fnCHRO_ID>
--          <2012/08/27><Albert.Chen><修改欄位fnRELA_ID為fsRELA_ID>
-- 記錄:<2014/08/21><Eric.Huang><新增 fsEPISODE/fnEPIPART/fsOTHTYPE1/fsOTHTYPE2/fsOTHTYPE3>
-- 記錄:<2016/11/04><David.Sin><刪除 fsEPISODE/fnEPIPART/fsOTHTYPE1/fsOTHTYPE2/fsOTHTYPE3/fsGROUPS>
-- =============================================
CREATE PROCEDURE [dbo].[spGET_SUBJECT]
	@fsSUBJ_ID	VARCHAR(12)
AS
BEGIN
 	SET NOCOUNT ON;

	SELECT 

		tbmSUBJECT.fsSUBJ_ID, 
		tbmSUBJECT.fsTITLE, 
		tbmSUBJECT.fsDESCRIPTION,
		tbmSUBJECT.fnDIR_ID, 
		tbmSUBJECT.fsTYPE1, 
		tbmSUBJECT.fsTYPE2, 
		tbmSUBJECT.fsTYPE3, 
	    fsATTRIBUTE1, fsATTRIBUTE2, fsATTRIBUTE3, 
		fsATTRIBUTE4, fsATTRIBUTE5, fsATTRIBUTE6, fsATTRIBUTE7, fsATTRIBUTE8, fsATTRIBUTE9, fsATTRIBUTE10,
		fsATTRIBUTE11, fsATTRIBUTE12, fsATTRIBUTE13, fsATTRIBUTE14, fsATTRIBUTE15, fsATTRIBUTE16, fsATTRIBUTE17,
		fsATTRIBUTE18, fsATTRIBUTE19, fsATTRIBUTE20, fsATTRIBUTE21, fsATTRIBUTE22, fsATTRIBUTE23, fsATTRIBUTE24,
		fsATTRIBUTE25, fsATTRIBUTE26, fsATTRIBUTE27, fsATTRIBUTE28, fsATTRIBUTE29, fsATTRIBUTE30, fsATTRIBUTE31,
		fsATTRIBUTE32, fsATTRIBUTE33, fsATTRIBUTE34, fsATTRIBUTE35, fsATTRIBUTE36, fsATTRIBUTE37, fsATTRIBUTE38, 
		fsATTRIBUTE39, fsATTRIBUTE40, fsATTRIBUTE41, fsATTRIBUTE42, fsATTRIBUTE43, fsATTRIBUTE44, fsATTRIBUTE45,
		fsATTRIBUTE46, fsATTRIBUTE47, fsATTRIBUTE48, fsATTRIBUTE49, fsATTRIBUTE50, 
		tbmSUBJECT.fdCREATED_DATE,
		tbmSUBJECT.fsCREATED_BY , 
		tbmSUBJECT.fdUPDATED_DATE, 
		tbmSUBJECT.fsUPDATED_BY,
		_sDIR_PATH = dbo.fnGET_DIR_PATH_BY_SUBJECT_ID(@fsSUBJ_ID),
		_sSUBJ_PATH = dbo.fnGET_SUBJ_PATH_BY_SUBJECT_ID(@fsSUBJ_ID),
		_sTYPE1 = (CASE WHEN (fsTYPE1 = '') THEN '(未選擇)' ELSE ISNULL(CODE1.fsNAME, '錯誤代碼: '+fsTYPE1) END),
		_sTYPE2 = (CASE WHEN (fsTYPE2 = '') THEN '(未選擇)' ELSE ISNULL(CODE2.fsNAME, '錯誤代碼: '+fsTYPE2) END),
		_sTYPE3 = (CASE WHEN (fsTYPE3 = '') THEN '(未選擇)' ELSE ISNULL(CODE3.fsNAME, '錯誤代碼: '+fsTYPE3) END),
		ISNULL(USERS_CRT.fsNAME,'') AS fsCREATED_BY_NAME,
		ISNULL(USERS_UPD.fsNAME,'') AS fsUPDATED_BY_NAME
	FROM
		tbmSUBJECT
		
		LEFT JOIN tbzCODE AS CODE1 ON (fsTYPE1 = CODE1.fsCODE) AND (CODE1.fsCODE_ID = 'ARC001')
		LEFT JOIN tbzCODE AS CODE2 ON (fsTYPE2 = CODE2.fsCODE) AND (CODE2.fsCODE_ID = 'ARC002')
		LEFT JOIN tbzCODE AS CODE3 ON (fsTYPE3 = CODE3.fsCODE) AND (CODE3.fsCODE_ID = 'ARC003')	
		LEFT JOIN tbmUSERS USERS_CRT ON tbmSUBJECT.fsCREATED_BY = USERS_CRT.fsLOGIN_ID
		LEFT JOIN tbmUSERS USERS_UPD ON tbmSUBJECT.fsUPDATED_BY = USERS_UPD.fsLOGIN_ID		
	WHERE
		(@fsSUBJ_ID = '' OR fsSUBJ_ID = @fsSUBJ_ID)
END


