

 
-- =============================================
-- 描述:	新增 SUBJECT 媒資主檔 資料
-- 記錄:	<2011/09/15><Eric.Huang><新增本預存>
-- 記錄:	<2014/08/21><Eric.Huang><新增 fsEPISODE/fnEPIPART/fsOTHTYPE1/fsOTHTYPE2/fsOTHTYPE3>
-- 記錄:	<2016/11/04><David.Sin><刪除 fsEPISODE/fnEPIPART/fsOTHTYPE1/fsOTHTYPE2/fsOTHTYPE3/fsGROUPs>
-- 記錄:	<2019/05/29><David.Sin><增加參數fnPRE_ID，若大於0則使用預編詮釋資料>
-- =============================================
CREATE PROCEDURE [dbo].[spINSERT_SUBJECT]

	@fsTITLE			NVARCHAR(100) = '',
	@fsDESCRIPTION		NVARCHAR(200) = '',
	@fnDIR_ID			BIGINT,
	@fsTYPE1			NVARCHAR(10) = '',
	@fsTYPE2			NVARCHAR(10) = '',
	@fsTYPE3			NVARCHAR(10) = '',
	@fnPRE_ID			BIGINT = 0,

	@fsATTRIBUTE1		NVARCHAR(MAX) = '',
	@fsATTRIBUTE2		NVARCHAR(MAX) = '',
	@fsATTRIBUTE3		NVARCHAR(MAX) = '',
	@fsATTRIBUTE4		NVARCHAR(MAX) = '',
	@fsATTRIBUTE5		NVARCHAR(MAX) = '',
	@fsATTRIBUTE6		NVARCHAR(MAX) = '',
	@fsATTRIBUTE7		NVARCHAR(MAX) = '',
	@fsATTRIBUTE8		NVARCHAR(MAX) = '',
	@fsATTRIBUTE9		NVARCHAR(MAX) = '',
	@fsATTRIBUTE10		NVARCHAR(MAX) = '',
	@fsATTRIBUTE11		NVARCHAR(MAX) = '',
	@fsATTRIBUTE12		NVARCHAR(MAX) = '',
	@fsATTRIBUTE13		NVARCHAR(MAX) = '',
	@fsATTRIBUTE14		NVARCHAR(MAX) = '',
	@fsATTRIBUTE15		NVARCHAR(MAX) = '',
	@fsATTRIBUTE16		NVARCHAR(MAX) = '',
	@fsATTRIBUTE17		NVARCHAR(MAX) = '',
	@fsATTRIBUTE18		NVARCHAR(MAX) = '',
	@fsATTRIBUTE19		NVARCHAR(MAX) = '',
	@fsATTRIBUTE20		NVARCHAR(MAX) = '',
	@fsATTRIBUTE21		NVARCHAR(MAX) = '',
	@fsATTRIBUTE22		NVARCHAR(MAX) = '',
	@fsATTRIBUTE23		NVARCHAR(MAX) = '',
	@fsATTRIBUTE24		NVARCHAR(MAX) = '',
	@fsATTRIBUTE25		NVARCHAR(MAX) = '',
	@fsATTRIBUTE26		NVARCHAR(MAX) = '',
	@fsATTRIBUTE27		NVARCHAR(MAX) = '',
	@fsATTRIBUTE28		NVARCHAR(MAX) = '',
	@fsATTRIBUTE29		NVARCHAR(MAX) = '',
	@fsATTRIBUTE30		NVARCHAR(MAX) = '',
	@fsATTRIBUTE31		NVARCHAR(MAX) = '',
	@fsATTRIBUTE32		NVARCHAR(MAX) = '',
	@fsATTRIBUTE33		NVARCHAR(MAX) = '',
	@fsATTRIBUTE34		NVARCHAR(MAX) = '',
	@fsATTRIBUTE35		NVARCHAR(MAX) = '',
	@fsATTRIBUTE36		NVARCHAR(MAX) = '',
	@fsATTRIBUTE37		NVARCHAR(MAX) = '',
	@fsATTRIBUTE38		NVARCHAR(MAX) = '',
	@fsATTRIBUTE39		NVARCHAR(MAX) = '',
	@fsATTRIBUTE40		NVARCHAR(MAX) = '',
	@fsATTRIBUTE41		NVARCHAR(MAX) = '',
	@fsATTRIBUTE42		NVARCHAR(MAX) = '',
	@fsATTRIBUTE43		NVARCHAR(MAX) = '',
	@fsATTRIBUTE44		NVARCHAR(MAX) = '',
	@fsATTRIBUTE45		NVARCHAR(MAX) = '',
	@fsATTRIBUTE46		NVARCHAR(MAX) = '',
	@fsATTRIBUTE47		NVARCHAR(MAX) = '',
	@fsATTRIBUTE48		NVARCHAR(MAX) = '',
	@fsATTRIBUTE49		NVARCHAR(MAX) = '',
	@fsATTRIBUTE50		NVARCHAR(MAX) = '',
	@fsCREATED_BY		NVARCHAR(50)

AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @SUBJ_ID VARCHAR(12)
	-----SET @SUBJ_ID = dbo.fnGET_SUBJECT_ID()
	DECLARE
		@fsTYPE		VARCHAR(10)	= 'SUBJECT',
		@fsNAME		NVARCHAR(10)= '主題檔',
		@fsHEAD		VARCHAR(10)	= CONVERT(VARCHAR(8), getdate(), 112),
		@fsBODY		VARCHAR(10)	= '',
		@fsNO_L		INT			= 4,
		@BY			VARCHAR(50) = @fsCREATED_BY
		
		SET NOCOUNT ON;

		/*還沒有此筆設定時先新增*/
		IF NOT EXISTS(SELECT * FROM tblNO WHERE (fsTYPE = @fsTYPE) AND (fsHEAD = @fsHEAD))
		BEGIN
			BEGIN TRY
				INSERT	tblNO
				SELECT	@fsTYPE, @fsNAME, @fsHEAD, @fsBODY, 0, @fsNO_L, GETDATE(), @BY, '1900/01/01', ''
			END TRY
			BEGIN CATCH
			END CATCH
		END

		DECLARE	@strRESULT	VARCHAR(100) = '',
				@intPRESENT	INT,
				@intNEW	INT,
				@blGETOK	BIT = 0,
				@dateTIME	DATETIME

		WHILE(@blGETOK = 0)
		BEGIN
			SET @dateTIME = GETDATE(); --先取出目前資料庫中的資料時間
			SET @intPRESENT =  (SELECT fsNO FROM tblNO WHERE (fsTYPE = @fsTYPE) AND (fsHEAD = @fsHEAD))
			SET @intNEW = @intPRESENT + 1
			SET @strRESULT = CAST(@intNEW AS VARCHAR(100))
			
			--WHILE(LEN(@strRESULT) < @fsNO_L)	
			--BEGIN
			--	SET @strRESULT = '0' + @strRESULT --依照長度來補0
			--END	
			
			/*修改回資料庫同時,檢查是否資料庫中的時間是比我取號時舊的資料*/
			UPDATE	tblNO
			SET		fsNO = @intNEW, fsUPDATED_BY = @BY
			WHERE	(fsTYPE = @fsTYPE) AND (fsHEAD = @fsHEAD) AND 
					(fdCREATED_DATE <= @dateTIME) AND (fdUPDATED_DATE <= @dateTIME)	
			
			IF (@@ROWCOUNT > 0)
				BEGIN
					/*確實有修改到比較舊的資料時*/
					SET @blGETOK = 1
				END
		END

		SET @strRESULT = '00000000000000000000000000000000000000000000000000' + CAST(@intNEW AS VARCHAR(50)) 
		SET @strRESULT = SUBSTRING(@strRESULT, LEN(@strRESULT)-@fsNO_L+1, @fsNO_L) 

		SET @SUBJ_ID = @fsHEAD + @fsBODY + @strRESULT
	-----

	BEGIN TRY
		
		BEGIN TRANSACTION

		IF(@fnPRE_ID = 0)
		BEGIN
			INSERT
				tbmSUBJECT
			
				(fsSUBJ_ID, fsTITLE , fsDESCRIPTION, fnDIR_ID,      fsTYPE1,       fsTYPE2,		fsTYPE3,	
				 fsATTRIBUTE1,  fsATTRIBUTE2,  fsATTRIBUTE3,  fsATTRIBUTE4,  fsATTRIBUTE5,  fsATTRIBUTE6,
				 fsATTRIBUTE7,  fsATTRIBUTE8,  fsATTRIBUTE9,  fsATTRIBUTE10, fsATTRIBUTE11, fsATTRIBUTE12,
				 fsATTRIBUTE13, fsATTRIBUTE14, fsATTRIBUTE15, fsATTRIBUTE16, fsATTRIBUTE17, fsATTRIBUTE18,
				 fsATTRIBUTE19, fsATTRIBUTE20, fsATTRIBUTE21, fsATTRIBUTE22, fsATTRIBUTE23, fsATTRIBUTE24,
				 fsATTRIBUTE25, fsATTRIBUTE26, fsATTRIBUTE27, fsATTRIBUTE28, fsATTRIBUTE29, fsATTRIBUTE30,
				 fsATTRIBUTE31, fsATTRIBUTE32, fsATTRIBUTE33, fsATTRIBUTE34, fsATTRIBUTE35, fsATTRIBUTE36,
				 fsATTRIBUTE37, fsATTRIBUTE38, fsATTRIBUTE39, fsATTRIBUTE40, fsATTRIBUTE41, fsATTRIBUTE42,
				 fsATTRIBUTE43, fsATTRIBUTE44, fsATTRIBUTE45, fsATTRIBUTE46, fsATTRIBUTE47, fsATTRIBUTE48,
				 fsATTRIBUTE49, fsATTRIBUTE50, fdCREATED_DATE, fsCREATED_BY)	
			 
			VALUES
		
				(@SUBJ_ID, @fsTITLE , @fsDESCRIPTION, @fnDIR_ID,      @fsTYPE1,       @fsTYPE2,		 @fsTYPE3,	
				 @fsATTRIBUTE1,  @fsATTRIBUTE2,  @fsATTRIBUTE3,  @fsATTRIBUTE4,  @fsATTRIBUTE5,  @fsATTRIBUTE6,
				 @fsATTRIBUTE7,  @fsATTRIBUTE8,  @fsATTRIBUTE9,  @fsATTRIBUTE10, @fsATTRIBUTE11, @fsATTRIBUTE12,
				 @fsATTRIBUTE13, @fsATTRIBUTE14, @fsATTRIBUTE15, @fsATTRIBUTE16, @fsATTRIBUTE17, @fsATTRIBUTE18,
				 @fsATTRIBUTE19, @fsATTRIBUTE20, @fsATTRIBUTE21, @fsATTRIBUTE22, @fsATTRIBUTE23, @fsATTRIBUTE24,
				 @fsATTRIBUTE25, @fsATTRIBUTE26, @fsATTRIBUTE27, @fsATTRIBUTE28, @fsATTRIBUTE29, @fsATTRIBUTE30,
				 @fsATTRIBUTE31, @fsATTRIBUTE32, @fsATTRIBUTE33, @fsATTRIBUTE34, @fsATTRIBUTE35, @fsATTRIBUTE36,
				 @fsATTRIBUTE37, @fsATTRIBUTE38, @fsATTRIBUTE39, @fsATTRIBUTE40, @fsATTRIBUTE41, @fsATTRIBUTE42,
				 @fsATTRIBUTE43, @fsATTRIBUTE44, @fsATTRIBUTE45, @fsATTRIBUTE46, @fsATTRIBUTE47, @fsATTRIBUTE48,
				 @fsATTRIBUTE49, @fsATTRIBUTE50, GETDATE(),      @fsCREATED_BY)
			END
		ELSE
		BEGIN

			--判斷此預編用的樣板是否與此主題樣板相同
			IF((SELECT [fnTEMP_ID_SUBJECT] FROM [dbo].[tbmDIRECTORIES] WHERE fnDIR_ID = @fnDIR_ID) = 
				(SELECT fnTEMP_ID FROM tbmARC_PRE WHERE fnPRE_ID = @fnPRE_ID))
			BEGIN
				INSERT
					tbmSUBJECT
				
					(fsSUBJ_ID, fsTITLE , fsDESCRIPTION, fnDIR_ID,      fsTYPE1,       fsTYPE2,		fsTYPE3,	
					 fsATTRIBUTE1,  fsATTRIBUTE2,  fsATTRIBUTE3,  fsATTRIBUTE4,  fsATTRIBUTE5,  fsATTRIBUTE6,
					 fsATTRIBUTE7,  fsATTRIBUTE8,  fsATTRIBUTE9,  fsATTRIBUTE10, fsATTRIBUTE11, fsATTRIBUTE12,
					 fsATTRIBUTE13, fsATTRIBUTE14, fsATTRIBUTE15, fsATTRIBUTE16, fsATTRIBUTE17, fsATTRIBUTE18,
					 fsATTRIBUTE19, fsATTRIBUTE20, fsATTRIBUTE21, fsATTRIBUTE22, fsATTRIBUTE23, fsATTRIBUTE24,
					 fsATTRIBUTE25, fsATTRIBUTE26, fsATTRIBUTE27, fsATTRIBUTE28, fsATTRIBUTE29, fsATTRIBUTE30,
					 fsATTRIBUTE31, fsATTRIBUTE32, fsATTRIBUTE33, fsATTRIBUTE34, fsATTRIBUTE35, fsATTRIBUTE36,
					 fsATTRIBUTE37, fsATTRIBUTE38, fsATTRIBUTE39, fsATTRIBUTE40, fsATTRIBUTE41, fsATTRIBUTE42,
					 fsATTRIBUTE43, fsATTRIBUTE44, fsATTRIBUTE45, fsATTRIBUTE46, fsATTRIBUTE47, fsATTRIBUTE48,
					 fsATTRIBUTE49, fsATTRIBUTE50, fdCREATED_DATE, fsCREATED_BY)
				SELECT
					@SUBJ_ID,fsTITLE,fsDESCRIPTION,@fnDIR_ID,@fsTYPE1,@fsTYPE2,@fsTYPE3,
					fsATTRIBUTE1,  fsATTRIBUTE2,  fsATTRIBUTE3,  fsATTRIBUTE4,  fsATTRIBUTE5,  fsATTRIBUTE6,
					 fsATTRIBUTE7,  fsATTRIBUTE8,  fsATTRIBUTE9,  fsATTRIBUTE10, fsATTRIBUTE11, fsATTRIBUTE12,
					 fsATTRIBUTE13, fsATTRIBUTE14, fsATTRIBUTE15, fsATTRIBUTE16, fsATTRIBUTE17, fsATTRIBUTE18,
					 fsATTRIBUTE19, fsATTRIBUTE20, fsATTRIBUTE21, fsATTRIBUTE22, fsATTRIBUTE23, fsATTRIBUTE24,
					 fsATTRIBUTE25, fsATTRIBUTE26, fsATTRIBUTE27, fsATTRIBUTE28, fsATTRIBUTE29, fsATTRIBUTE30,
					 fsATTRIBUTE31, fsATTRIBUTE32, fsATTRIBUTE33, fsATTRIBUTE34, fsATTRIBUTE35, fsATTRIBUTE36,
					 fsATTRIBUTE37, fsATTRIBUTE38, fsATTRIBUTE39, fsATTRIBUTE40, fsATTRIBUTE41, fsATTRIBUTE42,
					 fsATTRIBUTE43, fsATTRIBUTE44, fsATTRIBUTE45, fsATTRIBUTE46, fsATTRIBUTE47, fsATTRIBUTE48,
					 fsATTRIBUTE49, fsATTRIBUTE50, GETDATE(),      @fsCREATED_BY
				FROM
					tbmARC_PRE
				WHERE
					fnPRE_ID = @fnPRE_ID
			END
			ELSE
			BEGIN
				
				SELECT RESULT = 'ERROR:此主題需要的樣板與預編詮釋資料的樣板不符'

			END
		END
		COMMIT	
		-- 新增完畢時, 取回新增資料的識別編號, 或OK字樣
		SELECT RESULT = @SUBJ_ID
	END TRY
	BEGIN CATCH
		ROLLBACK
		-- 發生例外時, 串回'ERROR:'開頭字串 + 錯誤碼 + 錯誤訊息
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH
END




