

-- =============================================
-- 描述:	根據使用者與目錄更新權限列表
-- 記錄:	<2011/11/04><David.Sin><新增本預存>
-- 記錄:	<2016/10/24><David.Sin><判斷是否已存在tbmDIR_USER>
-- =============================================
CREATE PROCEDURE [dbo].[spUPDATE_DIR_USER_BY_USER_DIR]
	@fnDIR_ID				BIGINT,
	@fsLOGIN_ID				NVARCHAR(256),
	@fsLIMIT_SUBJECT		VARCHAR(10),
	@fsLIMIT_VIDEO			VARCHAR(10),
	@fsLIMIT_AUDIO			VARCHAR(10),
	@fsLIMIT_PHOTO			VARCHAR(10),
	@fsLIMIT_DOC			VARCHAR(10),
	@fsUPDATED_BY			VARCHAR(50)
AS
BEGIN
 	SET NOCOUNT ON;

	BEGIN TRY
	
	IF EXISTS(SELECT * FROM tbmDIR_USER WHERE fnDIR_ID = @fnDIR_ID AND fsLOGIN_ID = @fsLOGIN_ID)
	BEGIN
		
		BEGIN TRANSACTION

		UPDATE
			tbmDIR_USER
		SET
			fsLIMIT_SUBJECT=@fsLIMIT_SUBJECT,
			fsLIMIT_VIDEO=@fsLIMIT_VIDEO,
			fsLIMIT_AUDIO=@fsLIMIT_AUDIO,
			fsLIMIT_PHOTO=@fsLIMIT_PHOTO,
			fsLIMIT_DOC=@fsLIMIT_DOC,
			fdUPDATED_DATE=GETDATE(),
			fsUPDATED_BY=@fsUPDATED_BY
		WHERE
			fnDIR_ID = @fnDIR_ID AND fsLOGIN_ID = @fsLOGIN_ID
		
		COMMIT	
	END
	ELSE
	BEGIN
		
		BEGIN TRANSACTION

		INSERT INTO tbmDIR_USER
		(fnDIR_ID,fsLOGIN_ID,fsLIMIT_SUBJECT,fsLIMIT_VIDEO,fsLIMIT_AUDIO,fsLIMIT_PHOTO,fsLIMIT_DOC,fdCREATED_DATE,fsCREATED_BY)
		VALUES
		(@fnDIR_ID,@fsLOGIN_ID,@fsLIMIT_SUBJECT,@fsLIMIT_VIDEO,@fsLIMIT_AUDIO,@fsLIMIT_PHOTO,@fsLIMIT_DOC,GETDATE(),@fsUPDATED_BY)
		
		COMMIT
	END		

	SELECT RESULT = ''

	END TRY
	BEGIN CATCH
		ROLLBACK
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH
END



