


-- =============================================
-- 描述:	依照FILE_NO取出ARC_AUDIO_D 入庫項目-聲音檔明細資料
-- 記錄:	<2012/09/25><Mihsiu.Chiu><新增本預存>
-- =============================================
CREATE PROCEDURE [dbo].[xsp_t_view_GET_ARC_AUDIO_D_BY_FILE_NO]
	@fsFILE_NO	VARCHAR(16),
	@fnINDEX_ID	int
AS
BEGIN
 	SET NOCOUNT ON;

	BEGIN TRY
		SELECT 		
			--fnINDEX_ID, fnTEMP_ID, fsCODE_USED, 
			fsFILE_NO, fnSEQ_NO, fsSUBJECT_ID, fsTYPE, fsID, fnEPISODE, fsSUPERVISOR, 
			fsTITLE, fsDESCRIPTION, fsFILE_STATUS, fsOLD_FILE_NAME, fsCHANGE_FILE_NO, 
			fnDIR_ID, fsCHANNEL_ID, fsARC_ID, fsFROM, fsKEYFRAME_NO, 
			fsATTRIBUTE1, fsATTRIBUTE2, fsATTRIBUTE3, fsATTRIBUTE4, fsATTRIBUTE5, 
			fsATTRIBUTE6, fsATTRIBUTE7, fsATTRIBUTE8, fsATTRIBUTE9, fsATTRIBUTE10, 
			fsATTRIBUTE11, fsATTRIBUTE12, fsATTRIBUTE13, fsATTRIBUTE14, fsATTRIBUTE15, 
			fsATTRIBUTE16, fsATTRIBUTE17, fsATTRIBUTE18, fsATTRIBUTE19, fsATTRIBUTE20, 
			fsATTRIBUTE21, fsATTRIBUTE22, fsATTRIBUTE23, fsATTRIBUTE24, fsATTRIBUTE25, 
			fsATTRIBUTE26, fsATTRIBUTE27, fsATTRIBUTE28, fsATTRIBUTE29, fsATTRIBUTE30, 
			fsATTRIBUTE31, fsATTRIBUTE32, fsATTRIBUTE33, fsATTRIBUTE34, fsATTRIBUTE35, 
			fsATTRIBUTE36, fsATTRIBUTE37, fsATTRIBUTE38, fsATTRIBUTE39, fsATTRIBUTE40, 
			fsATTRIBUTE41, fsATTRIBUTE42, fsATTRIBUTE43, fsATTRIBUTE44, fsATTRIBUTE45, 
			fsATTRIBUTE46, fsATTRIBUTE47, fsATTRIBUTE48, fsATTRIBUTE49, fsATTRIBUTE50, 
			fsGROUPS, fdCREATED_DATE, fsCREATED_BY, fdUPDATED_DATE, fsUPDATED_BY, 			
			
			--_sIMAGE_URL = dbo.fnGET_IMAGE_URL_BY_DataType_AND_FILE_NO('A',fsFILE_NO),
			--_sFILE_PATH = dbo.fnGET_FILE_PATH_BY_DataType_AND_FILE_NO('A',fsFILE_NO),
			
			_sFILE_URL = dbo.fn_t_view_GET_FILE_URL_BY_TYPE_AND_FILE_NO('A',fsFILE_NO,''),
			_sFILE_URL_H = dbo.fn_t_view_GET_FILE_URL_BY_TYPE_AND_FILE_NO('A',fsFILE_NO,'H'),
			_sFILE_URL_L = dbo.fn_t_view_GET_FILE_URL_BY_TYPE_AND_FILE_NO('A',fsFILE_NO,'L'),
			
			_sIMAGE_URL = dbo.fn_t_view_GET_IMAGE_URL_BY_TYPE_AND_FILE_NO('A',fsFILE_NO),
			
			_sFILE_INFO = dbo.fnGET_FILE_INFO_BY_DataType_AND_FILE_NO('A',fsFILE_NO),
			
			_sDIR_PATH = dbo.fnGET_DIR_PATH_BY_SUBJECT_ID(fsSUBJECT_ID),
			_sSUBJ_PATH = dbo.fnGET_SUBJ_PATH_BY_SUBJECT_ID(fsSUBJECT_ID)
			
			,fdBEG_TIME, fdEND_TIME, fdDURATION --201205一堆欄位調整
			, fnRESP_ID
	    	,_sBEG_TIME = dbo.fnGET_TIMECODE_FROM_SECONDS(fdBEG_TIME)
			,_sEND_TIME = dbo.fnGET_TIMECODE_FROM_SECONDS(fdEND_TIME)
		FROM
			t_tbmARC_AUDIO_D
			
		WHERE
			(fsFILE_NO = @fsFILE_NO and fnINDEX_ID = @fnINDEX_ID)

	END TRY
	BEGIN CATCH
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH
END



