

-- =============================================
-- 描述:	依照登入日期或登入者或執行動作 取出L_TRAN主檔資料
-- 記錄:	<2012/02/13><Mihsiu.Chiu><新增本預存>
-- 記錄:	<2013/05/24><Eric.Huang><由Declare @xxx table 改為 create table #xxx , 速度變快很多!>
-- 記錄:	<2013/10/03><Eric.Huang><fsNOTE放入FILE_NO + FSTITLE>
-- 記錄:	<2017/02/21><David.Sin><修改本預存>
-- =============================================
CREATE PROCEDURE [dbo].[xspGET_L_TRAN_BY_DATES_USERNAME_ACTIONTYPE_TABLENAME]
	@fdDATE1	VARCHAR(10),
	@fdDATE2	VARCHAR(10)
AS
BEGIN
 	SET NOCOUNT ON;

	BEGIN TRY		
	
		--篩選資料
		SELECT 
			fnTRAN_ID,tblTRANSACTION.fsFILE_NO, fsTABLE_NAME, fsACTION_TYPE,
			fdCREATED_DATE, fsCREATED_BY,
			_sTABLE_NAME = (CASE WHEN (fsTABLE_NAME = '') THEN '(未選擇)' 
								ELSE ISNULL(CODE.fsNAME, '錯誤代碼: '+fsTABLE_NAME) END),
			_sACTION_TYPE = (CASE WHEN (fsACTION_TYPE = 'INSERT') THEN '新增'
								  WHEN (fsACTION_TYPE = 'QUERY') THEN '查詢'
								  WHEN (fsACTION_TYPE = 'UPDATE') THEN '修改'
								  WHEN (fsACTION_TYPE = 'DELETE') THEN '刪除'
								  ELSE '(未選擇)' END)

		FROM
			tblTRANSACTION
			LEFT JOIN (select fsCODE, fsNAME from tbzCODE where fsCODE_ID = 'LOG003') AS CODE ON (fsTABLE_NAME = CODE.fsCODE)
			LEFT JOIN (SELECT fsFILE_NO, fsTITLE FROM tbmARC_VIDEO)   AS ARC_VIDEO   ON (fsTABLE_NAME = 'tbmARC_VIDEO' AND ARC_VIDEO.fsFILE_NO   = tblTRANSACTION.fsFILE_NO)
			LEFT JOIN (SELECT fsFILE_NO, fsTITLE FROM tbmARC_AUDIO)   AS ARC_AUDIO   ON (fsTABLE_NAME = 'tbmARC_AUDIO' AND ARC_AUDIO.fsFILE_NO   = tblTRANSACTION.fsFILE_NO)
			LEFT JOIN (SELECT fsFILE_NO, fsTITLE FROM tbmARC_PHOTO)   AS ARC_PHOTO   ON (fsTABLE_NAME = 'tbmARC_PHOTO' AND ARC_PHOTO.fsFILE_NO   = tblTRANSACTION.fsFILE_NO)
			LEFT JOIN (SELECT fsFILE_NO, fsTITLE FROM tbmARC_DOC)     AS ARC_DOC     ON (fsTABLE_NAME = 'tbmARC_DOC'   AND ARC_DOC.fsFILE_NO     = tblTRANSACTION.fsFILE_NO)
			LEFT JOIN (SELECT fsSUBJ_ID, fsTITLE FROM tbmSUBJECT)     AS [SUBJECT]   ON (fsTABLE_NAME = 'tbmSUBJECT'   AND [SUBJECT].fsSUBJ_ID   = tblTRANSACTION.fsFILE_NO)
			LEFT JOIN (SELECT fsFILE_NO, fsTITLE FROM t_tbmARC_VIDEO) AS t_ARC_VIDEO ON (fsTABLE_NAME = 'tbmARC_VIDEO' AND t_ARC_VIDEO.fsFILE_NO = tblTRANSACTION.fsFILE_NO)
			LEFT JOIN (SELECT fsFILE_NO, fsTITLE FROM t_tbmARC_AUDIO) AS t_ARC_AUDIO ON (fsTABLE_NAME = 'tbmARC_AUDIO' AND t_ARC_AUDIO.fsFILE_NO = tblTRANSACTION.fsFILE_NO)
			LEFT JOIN (SELECT fsFILE_NO, fsTITLE FROM t_tbmARC_PHOTO) AS t_ARC_PHOTO ON (fsTABLE_NAME = 'tbmARC_PHOTO' AND t_ARC_PHOTO.fsFILE_NO = tblTRANSACTION.fsFILE_NO)
			LEFT JOIN (SELECT fsFILE_NO, fsTITLE FROM t_tbmARC_DOC)   AS t_ARC_DOC   ON (fsTABLE_NAME = 'tbmARC_DOC'   AND t_ARC_DOC.fsFILE_NO   = tblTRANSACTION.fsFILE_NO)


		WHERE
			(@fdDATE1 = '' OR CONVERT(VARCHAR(10),fdCREATED_DATE,111) >= @fdDATE1) AND
			(@fdDATE2 = '' OR CONVERT(VARCHAR(10),fdCREATED_DATE,111) <= @fdDATE2)
		ORDER BY
			fdCREATED_DATE DESC
	END TRY
	BEGIN CATCH
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH
END


