


-- =============================================
-- 描述:	計算USER_GROUP主檔中各群組的統計人數
-- 記錄:	<2011/08/24><Eric.Huang><新增本預存>
-- =============================================
CREATE PROCEDURE [dbo].[xspGET_USERS_GROUPS_CNT_BY_GROUP]

AS
BEGIN
 	SET NOCOUNT ON;

	BEGIN TRY
		SELECT
			GROUPS.fsGROUP_ID, GROUPS.fsNAME, GROUPS.fsTYPE,GROUPS.fsDESCRIPTION, COUNT(USER_G.fsGROUP_ID) USER_COUNT, GROUPS.fdCREATED_DATE,
			GROUPS.fsCREATED_BY, GROUPS.fdUPDATED_DATE, GROUPS.fsUPDATED_BY
		FROM
			tbmGROUPS AS GROUPS
			LEFT JOIN tbmUSER_GROUP AS USER_G ON (USER_G.fsGROUP_ID = GROUPS.fsGROUP_ID)

		GROUP BY
			GROUPS.fsGROUP_ID ,GROUPS.fsNAME,GROUPS.fsTYPE, GROUPS.fsDESCRIPTION,GROUPS.fdCREATED_DATE,
			GROUPS.fsCREATED_BY, GROUPS.fdUPDATED_DATE, GROUPS.fsUPDATED_BY	

	END TRY
	BEGIN CATCH
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH
END


