

-- =============================================
-- 描述:	取出L_SRH 各TYPE資料BY TYPE & DATES
-- 記錄:	<2011/12/13><Eric.Huang><新增本預存>
-- =============================================
CREATE PROCEDURE [dbo].[xspGET_L_SRH_MULTI_TABLES_BY_TYPES_AND_DATES]

	@fsTYPE			VARCHAR(5),
	@fdSDATE		DATE,
	@fdEDATE		DATE
	
AS
BEGIN
 	SET NOCOUNT ON;

	BEGIN TRY
	
		--SET @fsTYPE = '3D'
		--SET @fdSDATE = DATEADD(DD,-10,GETDATE())
		--SET @fdEDATE = DATEADD(DD,5,GETDATE())
		
	    DECLARE @ssql VARCHAR(3000)
	    
	    --依傳入TYPE執行
		--SET @ssql = 'SELECT fdSDATE, fdEDATE, fsKEYWORD, fnCOUNT, fdCREATED_DATE, fsCREATED_BY FROM '
		--IF		(@fsTYPE = '3D') BEGIN SET @ssql = @ssql + ' tblSRH_CNT3D WHERE fdSDATE >= ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE <= ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''''	END
		--ELSE IF (@fsTYPE = '1W') BEGIN SET @ssql = @ssql + ' tblSRH_CNT1W WHERE fdSDATE >= ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE <= ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''''	END
		--ELSE IF (@fsTYPE = '1M') BEGIN SET @ssql = @ssql + ' tblSRH_CNT1M WHERE fdSDATE >= ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE <= ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''''	END
		--ELSE IF (@fsTYPE = '3M') BEGIN SET @ssql = @ssql + ' tblSRH_CNT3M WHERE fdSDATE >= ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE <= ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''''	END
		--ELSE IF (@fsTYPE = '1Y') BEGIN SET @ssql = @ssql + ' tblSRH_CNT1Y WHERE fdSDATE >= ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE <= ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''''	END

		--SET @ssql = @ssql + ' ORDER BY fnCOUNT DESC'
		
		--SELECT @ssql

		-- 一次全部執行
		IF (@fsTYPE = 'ALL') 
			BEGIN

			--有UNION,就不能使用ORDER BY 故用子句的子句語法
			SELECT *
			FROM
			(
			
				SELECT TOP(SELECT COUNT(fsKEYWORD) FROM tblSRH_CNT3D) '3D' AS TYPE, fdSDATE, fdEDATE, fsKEYWORD, fnCOUNT, fdCREATED_DATE, fsCREATED_BY FROM tblSRH_CNT3D WHERE fdSDATE = DATEADD(dd, -3, DATEDIFF(dd, 0, GETDATE())) AND fdEDATE = DATEADD(dd, -1, DATEDIFF(dd, 0, GETDATE())) ORDER BY fnCOUNT DESC , fsKEYWORD
				UNION ALL
				
				SELECT TOP(SELECT COUNT(fsKEYWORD) FROM tblSRH_CNT1W) '1W' AS TYPE, fdSDATE, fdEDATE, fsKEYWORD, fnCOUNT, fdCREATED_DATE, fsCREATED_BY FROM tblSRH_CNT1W WHERE fdSDATE = DATEADD(dd, -7, DATEDIFF(dd, 0, GETDATE())) AND fdEDATE = DATEADD(dd, -1, DATEDIFF(dd, 0, GETDATE())) ORDER BY fnCOUNT DESC , fsKEYWORD
				UNION ALL
				
				SELECT TOP(SELECT COUNT(fsKEYWORD) FROM tblSRH_CNT1M) '1M' AS TYPE, fdSDATE, fdEDATE, fsKEYWORD, fnCOUNT, fdCREATED_DATE, fsCREATED_BY FROM tblSRH_CNT1M WHERE fdSDATE = DATEADD(dd, -30, DATEDIFF(dd, 0, GETDATE())) AND fdEDATE = DATEADD(dd, -1, DATEDIFF(dd, 0, GETDATE())) ORDER BY fnCOUNT DESC , fsKEYWORD
				UNION ALL
				
				SELECT TOP(SELECT COUNT(fsKEYWORD) FROM tblSRH_CNT3M)  '3M' AS TYPE, fdSDATE, fdEDATE, fsKEYWORD, fnCOUNT, fdCREATED_DATE, fsCREATED_BY FROM tblSRH_CNT3M WHERE fdSDATE = DATEADD(dd, -90, DATEDIFF(dd, 0, GETDATE())) AND fdEDATE = DATEADD(dd, -1, DATEDIFF(dd, 0, GETDATE())) ORDER BY fnCOUNT DESC , fsKEYWORD
				UNION ALL
				
				SELECT TOP(SELECT COUNT(fsKEYWORD) FROM tblSRH_CNT1Y) '1Y' AS TYPE, fdSDATE, fdEDATE, fsKEYWORD, fnCOUNT, fdCREATED_DATE, fsCREATED_BY FROM tblSRH_CNT1Y WHERE fdSDATE = DATEADD(dd, -365, DATEDIFF(dd, 0, GETDATE())) AND fdEDATE = DATEADD(dd, -1, DATEDIFF(dd, 0, GETDATE())) ORDER BY fnCOUNT DESC , fsKEYWORD
			
			) TBL_ALL
			


			END
		ELSE
			BEGIN
				SET @ssql = 'SELECT fdSDATE, fdEDATE, fsKEYWORD, fnCOUNT, fdCREATED_DATE, fsCREATED_BY FROM '
				IF		(@fsTYPE = '3D') BEGIN SET @ssql = @ssql + ' tblSRH_CNT3D WHERE fdSDATE = ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE = ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''' + ORDER BY fnCOUNT DESC , fsKEYWORD'	END
				ELSE IF (@fsTYPE = '1W') BEGIN SET @ssql = @ssql + ' tblSRH_CNT1W WHERE fdSDATE = ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE = ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''' + ORDER BY fnCOUNT DESC , fsKEYWORD'	END
				ELSE IF (@fsTYPE = '1M') BEGIN SET @ssql = @ssql + ' tblSRH_CNT1M WHERE fdSDATE = ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE = ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''' + ORDER BY fnCOUNT DESC , fsKEYWORD'	END
				ELSE IF (@fsTYPE = '3M') BEGIN SET @ssql = @ssql + ' tblSRH_CNT3M WHERE fdSDATE = ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE = ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''' + ORDER BY fnCOUNT DESC , fsKEYWORD'	END
				ELSE IF (@fsTYPE = '1Y') BEGIN SET @ssql = @ssql + ' tblSRH_CNT1Y WHERE fdSDATE = ''' + CONVERT(VARCHAR(10),@fdSDATE,111) + ''' AND fdSDATE = ''' + CONVERT(VARCHAR(10),@fdEDATE,111) + ''' + ORDER BY fnCOUNT DESC , fsKEYWORD'	END

				SET @ssql = @ssql + ' ORDER BY fnCOUNT DESC'
				
				EXEC(@ssql)
			END
		
	END TRY
	
	BEGIN CATCH
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH
END




