CREATE PROCEDURE [dbo].[xspGET_WORK_MEDIAIMPORT]

@fnWAIT_CHECKFILE_STATUS	smallint,
@fnWAIT_CARBON_STATUS		smallint,
@fnWAIT_UNWRAP_STATUS		smallint,
@fnWAIT_CHECKIN_FILE_STATUS	smallint

AS

BEGIN

	SELECT * FROM tblMEDIAIMPORT 
	WHERE fnJOB_STATUS IN (@fnWAIT_CHECKFILE_STATUS, @fnWAIT_CARBON_STATUS, @fnWAIT_UNWRAP_STATUS, @fnWAIT_CHECKIN_FILE_STATUS)

END
