





-- =============================================
-- 描述:	取出全部 DIRECTORIES主檔資料 SPEED VERSION
-- 記錄:	<2015/01/24><Dennis.Wen><新增>
-- =============================================
CREATE PROCEDURE [dbo].[xspGET_DIRECTORIES_AND_SUBJECTS_ALL_SOON]

AS
BEGIN
	SET NOCOUNT ON;
	
	BEGIN TRY

DECLARE	@tblRESULT TABLE( LV0_NAME NVARCHAR(50), LV1_NAME NVARCHAR(50), LV2_NAME NVARCHAR(50), LV3_NAME NVARCHAR(50), LV4_NAME NVARCHAR(50), 
						  LV5_NAME NVARCHAR(50), LV6_NAME NVARCHAR(50), LV7_NAME NVARCHAR(50), LV8_NAME NVARCHAR(50), LV9_NAME NVARCHAR(50), 
						LV0_ORDER INT, LV1_ORDER INT, LV2_ORDER INT, LV3_ORDER INT, LV4_ORDER INT, 
						LV5_ORDER INT, LV6_ORDER INT, LV7_ORDER INT, LV8_ORDER INT, LV9_ORDER INT, 
						LV0_ID INT, LV1_ID INT, LV2_ID INT, LV3_ID INT, LV4_ID INT, 
						LV5_ID INT, LV6_ID INT, LV7_ID INT, LV8_ID INT, LV9_ID INT, _DIRTYPE VARCHAR(1), _DIRID BIGINT, _DIRPID BIGINT,  _SUBJLIST NVARCHAR(MAX), _DIRNAME NVARCHAR(50))

DECLARE @tblQUEUE TABLE (ID INT, DIR_ID INT, _LIST VARCHAR(50), _DIRTYPE VARCHAR(1), _DIRID BIGINT, _DIRPID BIGINT, _DIRNAME NVARCHAR(50)) 

-----

INSERT @tblQUEUE 
SELECT ROW_NUMBER() OVER(ORDER BY fnDIR_ID), fnDIR_ID, dbo.fnGET_DIR_PARENT_LIST(fnDIR_ID), fsDIRTYPE, fnDIR_ID, fnPARENT_ID, fsNAME
FROM tbmDIRECTORIES AS DD 
--WHERE fnDIR_ID NOT IN (select distinct [fnPARENT_ID] from [dbo].[tbmDIRECTORIES])

-----

INSERT	@tblRESULT
SELECT
		--ISNULL((CASE D0.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D0.fnDIR_ID AS VARCHAR(5)) + '__' + D0.fsNAME, ''), 
		--ISNULL((CASE D1.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D1.fnDIR_ID AS VARCHAR(5)) + '__' + D1.fsNAME, ''), 
		--ISNULL((CASE D2.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D2.fnDIR_ID AS VARCHAR(5)) + '__' + D2.fsNAME, ''), 
		--ISNULL((CASE D3.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D3.fnDIR_ID AS VARCHAR(5)) + '__' + D3.fsNAME, ''), 
		--ISNULL((CASE D4.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D4.fnDIR_ID AS VARCHAR(5)) + '__' + D4.fsNAME, ''),
		--ISNULL((CASE D5.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D5.fnDIR_ID AS VARCHAR(5)) + '__' + D5.fsNAME, ''), 
		--ISNULL((CASE D6.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D6.fnDIR_ID AS VARCHAR(5)) + '__' + D6.fsNAME, ''), 
		--ISNULL((CASE D7.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D7.fnDIR_ID AS VARCHAR(5)) + '__' + D7.fsNAME, ''), 
		--ISNULL((CASE D8.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D8.fnDIR_ID AS VARCHAR(5)) + '__' + D8.fsNAME, ''), 
		--ISNULL((CASE D9.fsDIRTYPE WHEN 'Q' THEN 'Q' ELSE 'D' END) + CAST(D9.fnDIR_ID AS VARCHAR(5)) + '__' + D9.fsNAME, ''),
		D0.fsNAME, 
		D1.fsNAME, 
		D2.fsNAME, 
		D3.fsNAME, 
		D4.fsNAME,
		D5.fsNAME, 
		D6.fsNAME, 
		D7.fsNAME, 
		D8.fsNAME, 
		D9.fsNAME,
		D0.fnORDER,	D1.fnORDER,	D2.fnORDER,	D3.fnORDER, D4.fnORDER,
		D5.fnORDER, D6.fnORDER,	D7.fnORDER,	D8.fnORDER, D9.fnORDER,
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 0),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 1),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 2),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 3),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 4),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 5),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 6),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 7),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 8),
		[dbo].[fnGET_ITEM_BY_INDEX](_LIST, 9),
		_DIRTYPE, _DIRID, _DIRPID,  '', _DIRNAME
FROM	@tblQUEUE AS Q
		LEFT JOIN tbmDIRECTORIES AS D0 ON (D0.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 0))
		LEFT JOIN tbmDIRECTORIES AS D1 ON (D1.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 1))
		LEFT JOIN tbmDIRECTORIES AS D2 ON (D2.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 2))
		LEFT JOIN tbmDIRECTORIES AS D3 ON (D3.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 3))
		LEFT JOIN tbmDIRECTORIES AS D4 ON (D4.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 4))
		LEFT JOIN tbmDIRECTORIES AS D5 ON (D5.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 5))
		LEFT JOIN tbmDIRECTORIES AS D6 ON (D6.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 6))
		LEFT JOIN tbmDIRECTORIES AS D7 ON (D7.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 7))
		LEFT JOIN tbmDIRECTORIES AS D8 ON (D8.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 8))
		LEFT JOIN tbmDIRECTORIES AS D9 ON (D9.fnDIR_ID = [dbo].[fnGET_ITEM_BY_INDEX](_LIST, 9))

-----
   


-----

--SELECT * FROM @tblQUEUE
SELECT * 
FROM @tblRESULT 
ORDER BY 
	LV0_ORDER, LV0_NAME, 
	LV1_ORDER, LV1_NAME, 
	LV2_ORDER, LV2_NAME, 
	LV3_ORDER, LV3_NAME, 
	LV4_ORDER, LV4_NAME 
	--LV0_NAME, LV1_NAME, LV2_NAME, LV3_NAME, LV4_NAME,
	--LV5_NAME, LV6_NAME, LV7_NAME, LV8_NAME, LV9_NAME


-----
   	

END TRY
	BEGIN CATCH
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH
END





