CREATE PROCEDURE [dbo].[xspINSERT_MEDIAIMPORT]

	@fsFILE_PATH		nvarchar(MAX),
	@fsJOB_GUID			varchar(64),
	@fnJOB_STATUS		smallint,
	@fsJOB_PARAMENTERS	nvarchar(MAX)

AS

BEGIN

	INSERT INTO tblMEDIAIMPORT(fsFILE_PATH, fsJOB_GUID, fnJOB_STATUS, fsJOB_PARAMENTERS, fdCREATE_DATE) VALUES(@fsFILE_PATH, @fsJOB_GUID, @fnJOB_STATUS, @fsJOB_PARAMENTERS, GETDATE())

END
