-- =============================================
-- Author:		<Dennis.Wen>
-- Create date: <2013/01/22>
-- Description:	<取得某段日期內上傳的影音圖文清單>
-- 記錄:	<2014/04/15><Albert.Chen><調整欄位fsDESCRIPTION長度為NVARCHAR(MAX)>
-- =============================================
CREATE PROCEDURE [dbo].[xspRPT_STD_GET_ARC_LIST_BY_DATES_01]
	@SDATE		DATE,
	@EDATE		DATE,
	@QUERY_BY	NVARCHAR(50)
AS
BEGIN
	--DECLARE
	--	@SDATE	DATE,
	--	@EDATE	DATE

	-------

	--SELECT
	--	@SDATE	= '2012/12/01',
	--	@EDATE	= '2012/12/31' 
	SET NOCOUNT ON;

	BEGIN TRY
		/*宣告變數*/
		--DECLARE @tblQUEUE TABLE(fnDIR_ID BIGINT)
		--DECLARE @tblSUBJECT TABLE(fnDIR_ID BIGINT, fsSUBJ_ID VARCHAR(12))
		DECLARE @tblRESULT TABLE(
			_sTYPE			VARCHAR(1),
			fsSUBJ_ID		VARCHAR(12),
			fsFILE_NO		VARCHAR(16),
			fsTITLE			NVARCHAR(100),
			fsDESCRIPTION	NVARCHAR(MAX),
			_sFILE_INFO		NVARCHAR(500), 
			fsCREATED_BY	NVARCHAR(50),
			fdCREATED_DATE	DATETIME,
			_WORK_ID        BIGINT
		)

		/*本程序不管權限和狀態*/
		
		/*取出結果:影*/
		INSERT	@tblRESULT
		SELECT	'1', fsSUBJECT_ID, fsFILE_NO, fsTITLE, fsDESCRIPTION, dbo.fnGET_FILE_INFO_BY_DataType_AND_FILE_NO('V', fsFILE_NO), --dbo.fnGET_IMAGE_URL_BY_TYPE_AND_FILE_NO('V', fsFILE_NO), 
		ARC.fsCREATED_BY, CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111), (SELECT TOP 1 fnWORK_ID FROM tblWORK AS W WHERE _ITEM_ID = fsFILE_NO ORDER BY W.fnWORK_ID )
		FROM	[tbmARC_VIDEO] AS ARC 
			--JOIN tblWORK WORK 
			--ON ARC.fsFILE_NO = WORK._ITEM_ID
		WHERE	(CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111) >= CONVERT(VARCHAR(10), @SDATE, 111)) AND
				(CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111) <= CONVERT(VARCHAR(10), @EDATE, 111))
		ORDER BY fdCREATED_DATE DESC 

		/*取出結果:音*/
		INSERT	@tblRESULT
		SELECT	'2', fsSUBJECT_ID, fsFILE_NO, fsTITLE, fsDESCRIPTION, dbo.fnGET_FILE_INFO_BY_DataType_AND_FILE_NO('A', fsFILE_NO), --dbo.fnGET_IMAGE_URL_BY_TYPE_AND_FILE_NO('A', fsFILE_NO), 
		ARC.fsCREATED_BY, CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111), (SELECT TOP 1 fnWORK_ID FROM tblWORK AS W WHERE _ITEM_ID = fsFILE_NO ORDER BY W.fnWORK_ID )
		FROM	[tbmARC_AUDIO] AS ARC
			--JOIN tblWORK WORK 
			--ON ARC.fsFILE_NO = WORK._ITEM_ID
		WHERE	(CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111) >= CONVERT(VARCHAR(10), @SDATE, 111)) AND
				(CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111) <= CONVERT(VARCHAR(10), @EDATE, 111))
		ORDER BY fdCREATED_DATE DESC 

		/*取出結果:圖*/
		INSERT	@tblRESULT
		SELECT	'3', fsSUBJECT_ID, fsFILE_NO, fsTITLE, fsDESCRIPTION, dbo.fnGET_FILE_INFO_BY_DataType_AND_FILE_NO('P', fsFILE_NO), --dbo.fnGET_IMAGE_URL_BY_TYPE_AND_FILE_NO('P', fsFILE_NO), 
		ARC.fsCREATED_BY, CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111), (SELECT TOP 1 fnWORK_ID FROM tblWORK AS W WHERE _ITEM_ID = fsFILE_NO ORDER BY W.fnWORK_ID )
		FROM	[tbmARC_PHOTO] AS ARC
			--JOIN tblWORK WORK 
			--ON ARC.fsFILE_NO = WORK._ITEM_ID
		WHERE	(CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111) >= CONVERT(VARCHAR(10), @SDATE, 111)) AND
				(CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111) <= CONVERT(VARCHAR(10), @EDATE, 111))
		ORDER BY fdCREATED_DATE DESC 

		/*取出結果:文*/
		INSERT	@tblRESULT
		SELECT	'4', fsSUBJECT_ID, fsFILE_NO, fsTITLE, fsDESCRIPTION, dbo.fnGET_FILE_INFO_BY_DataType_AND_FILE_NO('D', fsFILE_NO), --dbo.fnGET_IMAGE_URL_BY_TYPE_AND_FILE_NO('D', fsFILE_NO), 
		ARC.fsCREATED_BY, CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111), (SELECT TOP 1 fnWORK_ID FROM tblWORK AS W WHERE _ITEM_ID = fsFILE_NO ORDER BY W.fnWORK_ID )
		FROM	[tbmARC_DOC] AS ARC
			--JOIN tblWORK WORK 
			--ON ARC.fsFILE_NO = WORK._ITEM_ID
		WHERE	(CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111) >= CONVERT(VARCHAR(10), @SDATE, 111)) AND
				(CONVERT(VARCHAR(10), ARC.fdCREATED_DATE, 111) <= CONVERT(VARCHAR(10), @EDATE, 111))
		ORDER BY fdCREATED_DATE DESC 

		--SELECT *, _sTYPE_NAME = (CASE _sTYPE WHEN '1' THEN '影片'
		--									WHEN '2' THEN '聲音'
		--									WHEN '3' THEN '圖片'
		--									WHEN '4' THEN '文件' END)
		--		, _sFROM_NAME = (SELECT fsTYPE FROM dbo.tblWORK WHERE fnWORK_ID = _WORK_ID)
		--FROM @tblRESULT
		--ORDER BY fdCREATED_DATE, _sTYPE, fsFILE_NO

		SELECT DISTINCT
			_DATE = CONVERT(VARCHAR(10),fdCREATED_DATE,111), V = (SELECT COUNT(fsFILE_NO) FROM @tblRESULT AS I WHERE I._sTYPE = '1' and I.fdCREATED_DATE = O.fdCREATED_DATE)
														, A = (SELECT COUNT(fsFILE_NO) FROM @tblRESULT AS I WHERE I._sTYPE = '2' and I.fdCREATED_DATE = O.fdCREATED_DATE)
														, P = (SELECT COUNT(fsFILE_NO) FROM @tblRESULT AS I WHERE I._sTYPE = '3' and I.fdCREATED_DATE = O.fdCREATED_DATE)
														, D = (SELECT COUNT(fsFILE_NO) FROM @tblRESULT AS I WHERE I._sTYPE = '4' and I.fdCREATED_DATE = O.fdCREATED_DATE)
		FROM @tblRESULT	AS O
		


	END TRY
	BEGIN CATCH
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH 
END
