
-- =============================================
-- Author:		<Dennis.Wen>
-- Create date: <2013/01/22>
-- Description:	<取得某段日期內上傳的影音圖文清單>
-- 記錄:	<2014/04/15><Albert.Chen><調整欄位fsDESCRIPTION長度為NVARCHAR(MAX)>
-- =============================================
CREATE PROCEDURE [dbo].[xspRPT_STD_GET_CLK_LIST_BY_DATES_02]
	@SDATE		DATE,
	@EDATE		DATE,
	@QUERY_BY	NVARCHAR(50)
AS
BEGIN
	--DECLARE
	--	@SDATE	DATE,
	--	@EDATE	DATE

	-------

	--SELECT
	--	@SDATE	= '2012/12/01',
	--	@EDATE	= '2012/12/31' 

	-------

	SET NOCOUNT ON;

	BEGIN TRY

		/*宣告變數*/
		DECLARE @tblRESULT TABLE(
			_sTYPE			VARCHAR(1),
			fsSUBJ_ID		VARCHAR(12),
			fsFILE_NO		VARCHAR(16),
			fsTITLE			NVARCHAR(100),
			fsDESCRIPTION	NVARCHAR(MAX),
			_sFILE_INFO		NVARCHAR(500),
			
			fsCREATED_BY	NVARCHAR(50),
			fdCREATED_DATE	DATETIME,
			
			_DATE			VARCHAR(10),
			_ORDER			BIGINT
			
		)
		
		/**/
		INSERT	@tblRESULT
		SELECT	[fsTYPE], 
				[fsSUBJECT_ID] = (CASE WHEN ([fsTYPE] = 'V') THEN (SELECT fsSUBJECT_ID FROM tbmARC_VIDEO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
										 WHEN ([fsTYPE] = 'A') THEN (SELECT fsSUBJECT_ID FROM tbmARC_AUDIO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
										 WHEN ([fsTYPE] = 'P') THEN (SELECT fsSUBJECT_ID FROM tbmARC_PHOTO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
										 WHEN ([fsTYPE] = 'D') THEN (SELECT fsSUBJECT_ID FROM tbmARC_DOC AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
										 ELSE [fsSUBJECT_ID] END), 
				fsFILE_NO, 
				fsTITLE	= (CASE WHEN ([fsTYPE] = 'V') THEN (SELECT fsTITLE FROM tbmARC_VIDEO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
								WHEN ([fsTYPE] = 'A') THEN (SELECT fsTITLE FROM tbmARC_AUDIO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
								WHEN ([fsTYPE] = 'P') THEN (SELECT fsTITLE FROM tbmARC_PHOTO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
								WHEN ([fsTYPE] = 'D') THEN (SELECT fsTITLE FROM tbmARC_DOC AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
								ELSE (SELECT fsTITLE FROM tbmSUBJECT AS SUBJ WHERE SUBJ.fsSUBJ_ID = CLK.[fsSUBJECT_ID]) END), 
				fsDESCRIPTION	= (CASE WHEN ([fsTYPE] = 'V') THEN (SELECT fsDESCRIPTION FROM tbmARC_VIDEO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
										WHEN ([fsTYPE] = 'A') THEN (SELECT fsDESCRIPTION FROM tbmARC_AUDIO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
										WHEN ([fsTYPE] = 'P') THEN (SELECT fsDESCRIPTION FROM tbmARC_PHOTO AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
										WHEN ([fsTYPE] = 'D') THEN (SELECT fsDESCRIPTION FROM tbmARC_DOC AS ARC WHERE ARC.fsFILE_NO = CLK.fsFILE_NO)
										ELSE (SELECT fsDESCRIPTION FROM tbmSUBJECT AS SUBJ WHERE SUBJ.fsSUBJ_ID = CLK.[fsSUBJECT_ID]) END), 
				dbo.fnGET_FILE_INFO_BY_DataType_AND_FILE_NO('V', fsFILE_NO),fsCREATED_BY, fdCREATED_DATE, CONVERT(VARCHAR(10),fdCREATED_DATE,111),
				(CASE WHEN ([fsTYPE] = 'V') THEN 1
					WHEN ([fsTYPE] = 'A') THEN 2
					WHEN ([fsTYPE] = 'P') THEN 3
					WHEN ([fsTYPE] = 'D') THEN 4
					ELSE 0 END)
		FROM	[tblARC_CLK] CLK
		WHERE	(CONVERT(VARCHAR(10), CLK.fdCREATED_DATE, 111) >= CONVERT(VARCHAR(10), @SDATE, 111)) AND
				(CONVERT(VARCHAR(10), CLK.fdCREATED_DATE, 111) <= CONVERT(VARCHAR(10), @EDATE, 111))
		--GROUP BY [fsTYPE], [fsSUBJECT_ID], fsFILE_NO
		--ORDER BY
		
		--UPDATE	@tblRESULT
		--SET		fsSUBJ_ID = (CASE WHEN [fsTYPE] = 'V' THEN (SELECT fsSUBJECT_ID FROM tbmARC_VIDEO AS ARC WHERE ARC.fsFILE_NO = fsFILE_NO)
		--					 CASE WHEN [fsTYPE] = 'A' THEN (SELECT fsSUBJECT_ID FROM tbmARC_AUDIO AS ARC WHERE ARC.fsFILE_NO = fsFILE_NO)
		--					 CASE WHEN [fsTYPE] = 'P' THEN (SELECT fsSUBJECT_ID FROM tbmARC_PHOTO AS ARC WHERE ARC.fsFILE_NO = fsFILE_NO)
		--					 CASE WHEN [fsTYPE] = 'D' THEN (SELECT fsSUBJECT_ID FROM tbmARC_DOC AS ARC WHERE ARC.fsFILE_NO = fsFILE_NO) END)
			
		SELECT *, _sTYPE_NAME = (CASE WHEN _sTYPE = 'V' THEN '影片'
										WHEN _sTYPE = 'A' THEN '聲音'
										WHEN _sTYPE = 'P' THEN '圖片'
										WHEN _sTYPE = 'D' THEN '文件'
										WHEN _sTYPE = 'S' THEN '主題' END) FROM @tblRESULT
		ORDER BY _ORDER, fdCREATED_DATE--fsFILE_NO, fsSUBJ_ID 

	END TRY
	BEGIN CATCH
		SELECT RESULT = 'ERROR:' + CAST(@@ERROR AS VARCHAR(10)) + '-' + ERROR_MESSAGE()
	END CATCH 


END

