CREATE PROCEDURE [dbo].[xspUPDATE_MEDIAIMPORT_STATUS]

	@fsFILE_PATH	nvarchar(MAX),
	@fsJOB_GUID		varchar(64),
	@fnJOB_STATUS	smallint,
	@fsJOB_PARAMENTERS	nvarchar(MAX),
	@fsJOB_MESSAGE	nvarchar(MAX),
	@fsUPDATE_BY	varchar(64)

AS

BEGIN

	UPDATE
		tblMEDIAIMPORT
	SET
		fnJOB_STATUS = @fnJOB_STATUS,
		fsJOB_PARAMENTERS = @fsJOB_PARAMENTERS,
		fsJOB_MESSAGE = @fsJOB_MESSAGE,
		fdUPDATE_DATE = GETDATE(),
		fsUPDATE_BY = @fsUPDATE_BY
	WHERE
		fsJOB_GUID = @fsJOB_GUID AND 
		fsFILE_PATH = @fsFILE_PATH 

END
