

-- =============================================
-- 描述:	取出一個媒體檔自訂欄位中有用到的所有代碼
-- 記錄:	<2012/04/27><Dennis.Wen><新增本函數>
--      	<2012/08/30><Mihsiu.Chiu><修改@fsCODE_ID & @fsCODE_CTRL => varchar(20)>
--			<2012/09/24><Mihsiu.Chiu><修改tbmARC_AUDIO_D>
-- =============================================
CREATE FUNCTION [dbo].[fnGET_ARC_USED_CODE_LIST_BY_FILE_NO](
	@TYPE		VARCHAR(1),
	@FILE_NO	VARCHAR(16)
)
RETURNS VARCHAR(1000)
AS
BEGIN   
/*變數宣告*/
DECLARE
	@SUBJECT_ID			VARCHAR(12) = '',
	@DIR_ID				INT			= -1,
	@fnTEMP_ID_VIDEO	INT			= -1,
	@fnTEMP_ID_AUDIO	INT			= -1,
	@fnTEMP_ID_PHOTO	INT			= -1,
	@fnTEMP_ID_DOC		INT			= -1,
	@fnTEMP_ID			INT


/*取出所在的Queue之DIR_ID*/
SET @DIR_ID = dbo.fnGET_DIR_ID_BY_FILE_NO(@TYPE, @FILE_NO)


/*依照其類別在DID樣版設定中取出樣板TEMP_ID*/
SELECT
	@fnTEMP_ID = CASE @TYPE WHEN 'V' THEN fnTEMP_ID_VIDEO
							WHEN 'A' THEN fnTEMP_ID_AUDIO
							WHEN 'P' THEN fnTEMP_ID_PHOTO
							WHEN 'D' THEN fnTEMP_ID_DOC ELSE -1 END
FROM
	tbmDIRECTORIES
WHERE
	(fnDIR_ID = @DIR_ID)
	
/*取出所套用樣板的欄位設定*/
DECLARE	@tblTEMPLATE_FIELDS TABLE(	fsFIELD			VARCHAR(50), 
									fsFIELD_NAME	NVARCHAR(50), 
									fsFIELD_TYPE	VARCHAR(50), 
									fsCODE_ID		VARCHAR(20), 
									fnCODE_CNT		INT, 
									fsCODE_CTRL		VARCHAR(20))

INSERT
	@tblTEMPLATE_FIELDS
SELECT
	fsFIELD, fsFIELD_NAME, fsFIELD_TYPE, fsCODE_ID, fnCODE_CNT, fsCODE_CTRL
FROM
	tbmTEMPLATE_FIELDS
WHERE
	(fnTEMP_ID = @fnTEMP_ID) AND 
	(fsFIELD_TYPE = 'CODE') --設定為代碼的 
	
--SELECT * FROM @tblTEMPLATE_FIELDS
 
/*跑回圈*/ 
DECLARE CSR1 CURSOR FOR SELECT fsFIELD, fsFIELD_NAME, fsFIELD_TYPE, fsCODE_ID, fnCODE_CNT, fsCODE_CTRL FROM @tblTEMPLATE_FIELDS
DECLARE @fsFIELD		VARCHAR(50), 
		@fsFIELD_NAME	NVARCHAR(50), 
		@fsFIELD_TYPE	VARCHAR(50), 
		@fsCODE_ID		VARCHAR(20), 
		@fnCODE_CNT		INT, 
		@fsCODE_CTRL	VARCHAR(20)
		
DECLARE @sql			NVARCHAR(1000) = '',
		@CONTENT		VARCHAR(50) = '',
		@RESULT			VARCHAR(1000) = '', 
		@TABLE_NAME		VARCHAR(50) = ''
		
SET @TABLE_NAME = (CASE @TYPE WHEN 'V' THEN 'tbmARC_VIDEO_D'
							WHEN  'A' THEN 'tbmARC_AUDIO_D'
							WHEN  'P' THEN 'tbmARC_PHOTO'
							WHEN  'D' THEN 'tbmARC_DOC' ELSE '' END)

OPEN CSR1
	FETCH NEXT FROM CSR1 INTO @fsFIELD, @fsFIELD_NAME, @fsFIELD_TYPE, @fsCODE_ID, @fnCODE_CNT, @fsCODE_CTRL
	WHILE (@@FETCH_STATUS=0)
		BEGIN 
		---------開始處理每一筆資料
		 

		--SET @sql =	' SELECT @CONTENT = ' + @fsFIELD + 
		--			' FROM ' + @TABLE_NAME +
		--			' WHERE (fsFILE_NO = ''' + @FILE_NO + ''')' 
		--EXEC sp_executesql @sql,N'@CONTENT NVARCHAR(50) output',@CONTENT output  
		
		/*因為在使用者自訂函數中無法使用EXEC指令, 所以改用下述方式...太冗長了*/
		
		IF (@TYPE = 'V')
		BEGIN
			SELECT @CONTENT = CASE @fsFIELD WHEN 'fsATTRIBUTE1' THEN fsATTRIBUTE1 WHEN 'fsATTRIBUTE2' THEN fsATTRIBUTE2 WHEN 'fsATTRIBUTE3' THEN fsATTRIBUTE3  WHEN 'fsATTRIBUTE4' THEN fsATTRIBUTE4 WHEN 'fsATTRIBUTE5' THEN fsATTRIBUTE5
											WHEN 'fsATTRIBUTE6' THEN fsATTRIBUTE6 WHEN 'fsATTRIBUTE7' THEN fsATTRIBUTE7 WHEN 'fsATTRIBUTE8' THEN fsATTRIBUTE8  WHEN 'fsATTRIBUTE9' THEN fsATTRIBUTE9 WHEN 'fsATTRIBUTE10' THEN fsATTRIBUTE10
											WHEN 'fsATTRIBUTE11' THEN fsATTRIBUTE11 WHEN 'fsATTRIBUTE12' THEN fsATTRIBUTE12 WHEN 'fsATTRIBUTE13' THEN fsATTRIBUTE13  WHEN 'fsATTRIBUTE14' THEN fsATTRIBUTE14 WHEN 'fsATTRIBUTE15' THEN fsATTRIBUTE15
											WHEN 'fsATTRIBUTE16' THEN fsATTRIBUTE16 WHEN 'fsATTRIBUTE17' THEN fsATTRIBUTE17 WHEN 'fsATTRIBUTE18' THEN fsATTRIBUTE18  WHEN 'fsATTRIBUTE19' THEN fsATTRIBUTE19 WHEN 'fsATTRIBUTE20' THEN fsATTRIBUTE20
											WHEN 'fsATTRIBUTE21' THEN fsATTRIBUTE21 WHEN 'fsATTRIBUTE22' THEN fsATTRIBUTE22 WHEN 'fsATTRIBUTE23' THEN fsATTRIBUTE23  WHEN 'fsATTRIBUTE24' THEN fsATTRIBUTE24 WHEN 'fsATTRIBUTE25' THEN fsATTRIBUTE25
											WHEN 'fsATTRIBUTE26' THEN fsATTRIBUTE26 WHEN 'fsATTRIBUTE27' THEN fsATTRIBUTE27 WHEN 'fsATTRIBUTE28' THEN fsATTRIBUTE28  WHEN 'fsATTRIBUTE29' THEN fsATTRIBUTE29 WHEN 'fsATTRIBUTE30' THEN fsATTRIBUTE30
											WHEN 'fsATTRIBUTE31' THEN fsATTRIBUTE31 WHEN 'fsATTRIBUTE32' THEN fsATTRIBUTE32 WHEN 'fsATTRIBUTE33' THEN fsATTRIBUTE33  WHEN 'fsATTRIBUTE34' THEN fsATTRIBUTE34 WHEN 'fsATTRIBUTE35' THEN fsATTRIBUTE35
											WHEN 'fsATTRIBUTE36' THEN fsATTRIBUTE36 WHEN 'fsATTRIBUTE37' THEN fsATTRIBUTE37 WHEN 'fsATTRIBUTE38' THEN fsATTRIBUTE38  WHEN 'fsATTRIBUTE39' THEN fsATTRIBUTE39 WHEN 'fsATTRIBUTE40' THEN fsATTRIBUTE40
											WHEN 'fsATTRIBUTE41' THEN fsATTRIBUTE41 WHEN 'fsATTRIBUTE42' THEN fsATTRIBUTE42 WHEN 'fsATTRIBUTE43' THEN fsATTRIBUTE43  WHEN 'fsATTRIBUTE44' THEN fsATTRIBUTE44 WHEN 'fsATTRIBUTE45' THEN fsATTRIBUTE45
											WHEN 'fsATTRIBUTE46' THEN fsATTRIBUTE46 WHEN 'fsATTRIBUTE47' THEN fsATTRIBUTE47 WHEN 'fsATTRIBUTE48' THEN fsATTRIBUTE48  WHEN 'fsATTRIBUTE49' THEN fsATTRIBUTE49 WHEN 'fsATTRIBUTE50' THEN fsATTRIBUTE50 ELSE '' END
			FROM tbmARC_VIDEO WHERE (fsFILE_NO = @FILE_NO)
		END
		ELSE IF (@TYPE = 'A')
		BEGIN
			SELECT @CONTENT = CASE @fsFIELD WHEN 'fsATTRIBUTE1' THEN fsATTRIBUTE1 WHEN 'fsATTRIBUTE2' THEN fsATTRIBUTE2 WHEN 'fsATTRIBUTE3' THEN fsATTRIBUTE3  WHEN 'fsATTRIBUTE4' THEN fsATTRIBUTE4 WHEN 'fsATTRIBUTE5' THEN fsATTRIBUTE5
											WHEN 'fsATTRIBUTE6' THEN fsATTRIBUTE6 WHEN 'fsATTRIBUTE7' THEN fsATTRIBUTE7 WHEN 'fsATTRIBUTE8' THEN fsATTRIBUTE8  WHEN 'fsATTRIBUTE9' THEN fsATTRIBUTE9 WHEN 'fsATTRIBUTE10' THEN fsATTRIBUTE10
											WHEN 'fsATTRIBUTE11' THEN fsATTRIBUTE11 WHEN 'fsATTRIBUTE12' THEN fsATTRIBUTE12 WHEN 'fsATTRIBUTE13' THEN fsATTRIBUTE13  WHEN 'fsATTRIBUTE14' THEN fsATTRIBUTE14 WHEN 'fsATTRIBUTE15' THEN fsATTRIBUTE15
											WHEN 'fsATTRIBUTE16' THEN fsATTRIBUTE16 WHEN 'fsATTRIBUTE17' THEN fsATTRIBUTE17 WHEN 'fsATTRIBUTE18' THEN fsATTRIBUTE18  WHEN 'fsATTRIBUTE19' THEN fsATTRIBUTE19 WHEN 'fsATTRIBUTE20' THEN fsATTRIBUTE20
											WHEN 'fsATTRIBUTE21' THEN fsATTRIBUTE21 WHEN 'fsATTRIBUTE22' THEN fsATTRIBUTE22 WHEN 'fsATTRIBUTE23' THEN fsATTRIBUTE23  WHEN 'fsATTRIBUTE24' THEN fsATTRIBUTE24 WHEN 'fsATTRIBUTE25' THEN fsATTRIBUTE25
											WHEN 'fsATTRIBUTE26' THEN fsATTRIBUTE26 WHEN 'fsATTRIBUTE27' THEN fsATTRIBUTE27 WHEN 'fsATTRIBUTE28' THEN fsATTRIBUTE28  WHEN 'fsATTRIBUTE29' THEN fsATTRIBUTE29 WHEN 'fsATTRIBUTE30' THEN fsATTRIBUTE30
											WHEN 'fsATTRIBUTE31' THEN fsATTRIBUTE31 WHEN 'fsATTRIBUTE32' THEN fsATTRIBUTE32 WHEN 'fsATTRIBUTE33' THEN fsATTRIBUTE33  WHEN 'fsATTRIBUTE34' THEN fsATTRIBUTE34 WHEN 'fsATTRIBUTE35' THEN fsATTRIBUTE35
											WHEN 'fsATTRIBUTE36' THEN fsATTRIBUTE36 WHEN 'fsATTRIBUTE37' THEN fsATTRIBUTE37 WHEN 'fsATTRIBUTE38' THEN fsATTRIBUTE38  WHEN 'fsATTRIBUTE39' THEN fsATTRIBUTE39 WHEN 'fsATTRIBUTE40' THEN fsATTRIBUTE40
											WHEN 'fsATTRIBUTE41' THEN fsATTRIBUTE41 WHEN 'fsATTRIBUTE42' THEN fsATTRIBUTE42 WHEN 'fsATTRIBUTE43' THEN fsATTRIBUTE43  WHEN 'fsATTRIBUTE44' THEN fsATTRIBUTE44 WHEN 'fsATTRIBUTE45' THEN fsATTRIBUTE45
											WHEN 'fsATTRIBUTE46' THEN fsATTRIBUTE46 WHEN 'fsATTRIBUTE47' THEN fsATTRIBUTE47 WHEN 'fsATTRIBUTE48' THEN fsATTRIBUTE48  WHEN 'fsATTRIBUTE49' THEN fsATTRIBUTE49 WHEN 'fsATTRIBUTE50' THEN fsATTRIBUTE50 ELSE '' END
			FROM tbmARC_AUDIO WHERE (fsFILE_NO = @FILE_NO)
		END
		ELSE IF (@TYPE = 'P')
		BEGIN
			SELECT @CONTENT = CASE @fsFIELD WHEN 'fsATTRIBUTE1' THEN fsATTRIBUTE1 WHEN 'fsATTRIBUTE2' THEN fsATTRIBUTE2 WHEN 'fsATTRIBUTE3' THEN fsATTRIBUTE3  WHEN 'fsATTRIBUTE4' THEN fsATTRIBUTE4 WHEN 'fsATTRIBUTE5' THEN fsATTRIBUTE5
											WHEN 'fsATTRIBUTE6' THEN fsATTRIBUTE6 WHEN 'fsATTRIBUTE7' THEN fsATTRIBUTE7 WHEN 'fsATTRIBUTE8' THEN fsATTRIBUTE8  WHEN 'fsATTRIBUTE9' THEN fsATTRIBUTE9 WHEN 'fsATTRIBUTE10' THEN fsATTRIBUTE10
											WHEN 'fsATTRIBUTE11' THEN fsATTRIBUTE11 WHEN 'fsATTRIBUTE12' THEN fsATTRIBUTE12 WHEN 'fsATTRIBUTE13' THEN fsATTRIBUTE13  WHEN 'fsATTRIBUTE14' THEN fsATTRIBUTE14 WHEN 'fsATTRIBUTE15' THEN fsATTRIBUTE15
											WHEN 'fsATTRIBUTE16' THEN fsATTRIBUTE16 WHEN 'fsATTRIBUTE17' THEN fsATTRIBUTE17 WHEN 'fsATTRIBUTE18' THEN fsATTRIBUTE18  WHEN 'fsATTRIBUTE19' THEN fsATTRIBUTE19 WHEN 'fsATTRIBUTE20' THEN fsATTRIBUTE20
											WHEN 'fsATTRIBUTE21' THEN fsATTRIBUTE21 WHEN 'fsATTRIBUTE22' THEN fsATTRIBUTE22 WHEN 'fsATTRIBUTE23' THEN fsATTRIBUTE23  WHEN 'fsATTRIBUTE24' THEN fsATTRIBUTE24 WHEN 'fsATTRIBUTE25' THEN fsATTRIBUTE25
											WHEN 'fsATTRIBUTE26' THEN fsATTRIBUTE26 WHEN 'fsATTRIBUTE27' THEN fsATTRIBUTE27 WHEN 'fsATTRIBUTE28' THEN fsATTRIBUTE28  WHEN 'fsATTRIBUTE29' THEN fsATTRIBUTE29 WHEN 'fsATTRIBUTE30' THEN fsATTRIBUTE30
											WHEN 'fsATTRIBUTE31' THEN fsATTRIBUTE31 WHEN 'fsATTRIBUTE32' THEN fsATTRIBUTE32 WHEN 'fsATTRIBUTE33' THEN fsATTRIBUTE33  WHEN 'fsATTRIBUTE34' THEN fsATTRIBUTE34 WHEN 'fsATTRIBUTE35' THEN fsATTRIBUTE35
											WHEN 'fsATTRIBUTE36' THEN fsATTRIBUTE36 WHEN 'fsATTRIBUTE37' THEN fsATTRIBUTE37 WHEN 'fsATTRIBUTE38' THEN fsATTRIBUTE38  WHEN 'fsATTRIBUTE39' THEN fsATTRIBUTE39 WHEN 'fsATTRIBUTE40' THEN fsATTRIBUTE40
											WHEN 'fsATTRIBUTE41' THEN fsATTRIBUTE41 WHEN 'fsATTRIBUTE42' THEN fsATTRIBUTE42 WHEN 'fsATTRIBUTE43' THEN fsATTRIBUTE43  WHEN 'fsATTRIBUTE44' THEN fsATTRIBUTE44 WHEN 'fsATTRIBUTE45' THEN fsATTRIBUTE45
											WHEN 'fsATTRIBUTE46' THEN fsATTRIBUTE46 WHEN 'fsATTRIBUTE47' THEN fsATTRIBUTE47 WHEN 'fsATTRIBUTE48' THEN fsATTRIBUTE48  WHEN 'fsATTRIBUTE49' THEN fsATTRIBUTE49 WHEN 'fsATTRIBUTE50' THEN fsATTRIBUTE50 ELSE '' END
			FROM tbmARC_PHOTO WHERE (fsFILE_NO = @FILE_NO)
		END
		ELSE IF (@TYPE = 'D')
		BEGIN
			SELECT @CONTENT = CASE @fsFIELD WHEN 'fsATTRIBUTE1' THEN fsATTRIBUTE1 WHEN 'fsATTRIBUTE2' THEN fsATTRIBUTE2 WHEN 'fsATTRIBUTE3' THEN fsATTRIBUTE3  WHEN 'fsATTRIBUTE4' THEN fsATTRIBUTE4 WHEN 'fsATTRIBUTE5' THEN fsATTRIBUTE5
											WHEN 'fsATTRIBUTE6' THEN fsATTRIBUTE6 WHEN 'fsATTRIBUTE7' THEN fsATTRIBUTE7 WHEN 'fsATTRIBUTE8' THEN fsATTRIBUTE8  WHEN 'fsATTRIBUTE9' THEN fsATTRIBUTE9 WHEN 'fsATTRIBUTE10' THEN fsATTRIBUTE10
											WHEN 'fsATTRIBUTE11' THEN fsATTRIBUTE11 WHEN 'fsATTRIBUTE12' THEN fsATTRIBUTE12 WHEN 'fsATTRIBUTE13' THEN fsATTRIBUTE13  WHEN 'fsATTRIBUTE14' THEN fsATTRIBUTE14 WHEN 'fsATTRIBUTE15' THEN fsATTRIBUTE15
											WHEN 'fsATTRIBUTE16' THEN fsATTRIBUTE16 WHEN 'fsATTRIBUTE17' THEN fsATTRIBUTE17 WHEN 'fsATTRIBUTE18' THEN fsATTRIBUTE18  WHEN 'fsATTRIBUTE19' THEN fsATTRIBUTE19 WHEN 'fsATTRIBUTE20' THEN fsATTRIBUTE20
											WHEN 'fsATTRIBUTE21' THEN fsATTRIBUTE21 WHEN 'fsATTRIBUTE22' THEN fsATTRIBUTE22 WHEN 'fsATTRIBUTE23' THEN fsATTRIBUTE23  WHEN 'fsATTRIBUTE24' THEN fsATTRIBUTE24 WHEN 'fsATTRIBUTE25' THEN fsATTRIBUTE25
											WHEN 'fsATTRIBUTE26' THEN fsATTRIBUTE26 WHEN 'fsATTRIBUTE27' THEN fsATTRIBUTE27 WHEN 'fsATTRIBUTE28' THEN fsATTRIBUTE28  WHEN 'fsATTRIBUTE29' THEN fsATTRIBUTE29 WHEN 'fsATTRIBUTE30' THEN fsATTRIBUTE30
											WHEN 'fsATTRIBUTE31' THEN fsATTRIBUTE31 WHEN 'fsATTRIBUTE32' THEN fsATTRIBUTE32 WHEN 'fsATTRIBUTE33' THEN fsATTRIBUTE33  WHEN 'fsATTRIBUTE34' THEN fsATTRIBUTE34 WHEN 'fsATTRIBUTE35' THEN fsATTRIBUTE35
											WHEN 'fsATTRIBUTE36' THEN fsATTRIBUTE36 WHEN 'fsATTRIBUTE37' THEN fsATTRIBUTE37 WHEN 'fsATTRIBUTE38' THEN fsATTRIBUTE38  WHEN 'fsATTRIBUTE39' THEN fsATTRIBUTE39 WHEN 'fsATTRIBUTE40' THEN fsATTRIBUTE40
											WHEN 'fsATTRIBUTE41' THEN fsATTRIBUTE41 WHEN 'fsATTRIBUTE42' THEN fsATTRIBUTE42 WHEN 'fsATTRIBUTE43' THEN fsATTRIBUTE43  WHEN 'fsATTRIBUTE44' THEN fsATTRIBUTE44 WHEN 'fsATTRIBUTE45' THEN fsATTRIBUTE45
											WHEN 'fsATTRIBUTE46' THEN fsATTRIBUTE46 WHEN 'fsATTRIBUTE47' THEN fsATTRIBUTE47 WHEN 'fsATTRIBUTE48' THEN fsATTRIBUTE48  WHEN 'fsATTRIBUTE49' THEN fsATTRIBUTE49 WHEN 'fsATTRIBUTE50' THEN fsATTRIBUTE50 ELSE '' END
			FROM tbmARC_DOC WHERE (fsFILE_NO = @FILE_NO)
		END

		/*因為在使用者自訂函數中無法使用EXEC指令, 所以改用上述方式...太冗長了*/
		
		SET @RESULT = @RESULT + @fsCODE_ID + ':' + @CONTENT +
						(CASE @fsCODE_CTRL WHEN 'ComboBox' THEN ';' ELSE '' END) + '/'
	
		---------處理完畢每一筆資料
		FETCH NEXT FROM CSR1 INTO @fsFIELD, @fsFIELD_NAME, @fsFIELD_TYPE, @fsCODE_ID, @fnCODE_CNT, @fsCODE_CTRL
		END
Close CSR1
	 
--	--SELECT @RESULT
	RETURN @RESULT
--RETURN''
END



